//! MOL file generation (V2000 format).
//!
//! Generates MDL MOL files compatible with most molecular viewers.
//! Also generates a JSON sidecar with color/metadata information.

use crate::types::{AtomMetadata, Malecule, MaleculeMetadata, MaleculeSummary, Severity};
use std::fmt::Write;

/// Generates a V2000 MOL file string.
///
/// Format specification: <https://en.wikipedia.org/wiki/Chemical_table_file>
#[must_use]
pub fn generate_mol(malecule: &Malecule) -> String {
    let mut mol = String::with_capacity(1024);

    // Header block (3 lines)
    // Line 1: Molecule name
    writeln!(mol, "{}", malecule.name).ok();
    // Line 2: Program/timestamp line (we leave it mostly empty)
    writeln!(mol, "  malecule  3D").ok();
    // Line 3: Comment
    writeln!(mol, "Generated by cleave malecule").ok();

    // Counts line
    // Format: aaabbblllfffcccsssxxxrrrpppiiimmmvvvvvv
    // aaa = number of atoms
    // bbb = number of bonds
    // We only use atoms and bonds, rest are zeros
    writeln!(
        mol,
        "{:3}{:3}  0  0  0  0  0  0  0  0999 V2000",
        malecule.atoms.len(),
        malecule.bonds.len()
    )
    .ok();

    // Atom block
    // Format: x y z symbol mass_diff charge stereo h_count stereo_box valence h0
    for atom in &malecule.atoms {
        let (x, y, z) = atom.position;
        writeln!(
            mol,
            "{:10.4}{:10.4}{:10.4} {:<3} 0  0  0  0  0  0  0  0  0  0  0  0",
            x, y, z, atom.element.symbol
        )
        .ok();
    }

    // Bond block
    // Format: atom1 atom2 type stereo not_used topology reacting_center
    for bond in &malecule.bonds {
        writeln!(
            mol,
            "{:3}{:3}{:3}  0  0  0  0",
            bond.atom1 + 1, // MOL files are 1-indexed
            bond.atom2 + 1,
            bond.bond_type
        )
        .ok();
    }

    // End
    writeln!(mol, "M  END").ok();

    mol
}

/// Generates the JSON sidecar metadata.
#[must_use]
pub fn generate_metadata(malecule: &Malecule) -> MaleculeMetadata {
    let atoms: Vec<AtomMetadata> = malecule
        .atoms
        .iter()
        .map(|atom| AtomMetadata {
            index: atom.id,
            symbol: atom.element.symbol.to_string(),
            category: atom.category.clone(),
            severity: atom.severity,
            color: atom.severity.color().to_string(),
            trait_id: atom.trait_id.clone(),
            description: atom.description.clone(),
            evidence: atom.evidence.clone(),
        })
        .collect();

    let summary = MaleculeSummary {
        total_atoms: malecule.atoms.len(),
        total_bonds: malecule.bonds.len(),
        hostile: malecule
            .atoms
            .iter()
            .filter(|a| a.severity == Severity::Hostile)
            .count(),
        suspicious: malecule
            .atoms
            .iter()
            .filter(|a| a.severity == Severity::Suspicious)
            .count(),
        notable: malecule
            .atoms
            .iter()
            .filter(|a| a.severity == Severity::Notable)
            .count(),
        neutral: malecule
            .atoms
            .iter()
            .filter(|a| a.severity == Severity::Neutral)
            .count(),
    };

    MaleculeMetadata {
        name: malecule.name.clone(),
        formula: malecule.formula.clone(),
        atoms,
        summary,
    }
}

/// Generates JSON string for the metadata.
///
/// # Errors
/// Returns error if JSON serialization fails.
pub fn generate_metadata_json(malecule: &Malecule) -> Result<String, serde_json::Error> {
    let metadata = generate_metadata(malecule);
    serde_json::to_string_pretty(&metadata)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::elements::{BORON, CARBON, OXYGEN};
    use crate::types::Severity;

    #[test]
    fn test_generate_mol() {
        let mut m = Malecule::new("test");
        m.add_atom(CARBON, "".to_string(), Severity::Neutral);
        m.atoms[0].position = (0.0, 0.0, 0.0);

        m.add_atom(OXYGEN, "objectives".to_string(), Severity::Suspicious);
        m.atoms[1].position = (1.5, 0.0, 0.0);

        m.add_bond(0, 1, 1);

        let mol = generate_mol(&m);

        assert!(mol.contains("test"));
        assert!(mol.contains("V2000"));
        assert!(mol.contains("C  ")); // Carbon atom
        assert!(mol.contains("O  ")); // Oxygen atom
        assert!(mol.contains("M  END"));
    }

    #[test]
    fn test_generate_metadata() {
        let mut m = Malecule::new("test");
        m.formula = "CO".to_string();
        m.add_atom(CARBON, "".to_string(), Severity::Neutral);
        m.add_atom(OXYGEN, "objectives".to_string(), Severity::Suspicious);
        m.add_bond(0, 1, 1);

        let metadata = generate_metadata(&m);

        assert_eq!(metadata.name, "test");
        assert_eq!(metadata.formula, "CO");
        assert_eq!(metadata.atoms.len(), 2);
        assert_eq!(metadata.summary.total_atoms, 2);
        assert_eq!(metadata.summary.suspicious, 1);
        assert_eq!(metadata.summary.neutral, 1);
    }

    #[test]
    fn test_mol_indexing() {
        let mut m = Malecule::new("test");
        m.add_atom(CARBON, "".to_string(), Severity::Neutral);
        m.add_atom(OXYGEN, "objectives".to_string(), Severity::Neutral);
        m.add_atom(BORON, "micro-behaviors".to_string(), Severity::Neutral);
        m.add_bond(0, 1, 1);
        m.add_bond(0, 2, 1);

        let mol = generate_mol(&m);

        // MOL files use 1-based indexing, so bonds should be 1-2 and 1-3
        assert!(mol.contains("  1  2  1"));
        assert!(mol.contains("  1  3  1"));
    }
}
