//! Output formatting and reporting.
//!
//! This module handles formatting analysis results for different output modes:
//! - Human-readable terminal output with colors
//! - JSON output for machine consumption
//! - Summary classification for quick triage
//!
//! # Output Modes
//!
//! - Default: Human-readable with colored output
//! - `--json`: Full JSON report
//! - `--summary`: Quick classification only

#[allow(unused_imports)] // Used by binary target via format_human_single
use crate::malecule_bridge;
use crate::types::{AnalysisReport, Criticality, FileAnalysis, Finding};
use anyhow::Result;
use colored::Colorize;
use std::collections::{HashMap, HashSet};

/// Extract base trait ID for aggregation (strip ::variant suffix)
/// e.g., "well-known/malware/trojan/macos-stealer-cpp::variant" -> "well-known/malware/trojan/macos-stealer-cpp"
/// e.g., "objectives/credential-access/stealer/shell::system-wide" -> "objectives/credential-access/stealer/shell"
/// Trait IDs without a variant suffix are returned unchanged.
#[allow(dead_code)] // Used by binary target
#[must_use]
fn get_directory_path(id: &str) -> String {
    // Strip variant suffix (::variant) if present
    // The base trait ID (without variant) is used as the aggregation key
    id.split("::").next().unwrap_or(id).to_string()
}

/// Aggregated finding for a directory path
#[allow(dead_code)] // Used by binary target
#[derive(Clone)]
struct AggregatedFinding {
    /// The directory path (e.g., "execution/command/subprocess")
    directory: String,
    /// The best (highest criticality) finding
    best: Finding,
    /// All trait IDs that matched in this directory
    matched_traits: Vec<String>,
}

/// Aggregate findings by directory path, keeping highest criticality (then highest conf)
/// Returns findings with IDs set to directory paths and trait_refs containing all matched trait IDs
/// Internal findings (from code analyzers) are not aggregated - shown individually
#[allow(dead_code)] // Used by binary target
#[must_use]
pub(crate) fn aggregate_findings_by_directory(findings: &[Finding]) -> Vec<Finding> {
    let mut aggregated: HashMap<String, AggregatedFinding> = HashMap::new();
    let mut internal_findings = Vec::new();

    for finding in findings {
        // YAML traits with variants (containing "::") are always aggregated
        // Even if they have evidence from internal sources (like symbol matching)
        let has_variant_suffix = finding.id.contains("::");

        // Check if this is an internal finding (generated by code, not from YAML traits)
        let is_internal = !has_variant_suffix
            && !finding.evidence.is_empty()
            && finding.evidence.iter().any(|e| {
                // Internal sources (generated by analyzers, not from YAML traits)
                e.source == "codesign_parser"
                    || e.source == "binary_analyzer"
                    || e.source == "strings_extractor"
                    || e.source == "import_mapper"
            });

        // Internal findings bypass aggregation - they're shown individually
        if is_internal {
            internal_findings.push(finding.clone());
            continue;
        }

        let dir_path = get_directory_path(&finding.id);

        match aggregated.get_mut(&dir_path) {
            None => {
                aggregated.insert(
                    dir_path.clone(),
                    AggregatedFinding {
                        directory: dir_path,
                        best: finding.clone(),
                        matched_traits: vec![finding.id.clone()],
                    },
                );
            }
            Some(agg) => {
                // Add this trait ID to the list
                if !agg.matched_traits.contains(&finding.id) {
                    agg.matched_traits.push(finding.id.clone());
                }

                // Keep the one with higher criticality.
                // Ties: higher confidence, then lexicographically smaller id so
                // parallel trait evaluation order doesn't flip the displayed pick.
                let should_replace = finding.crit > agg.best.crit
                    || (finding.crit == agg.best.crit && finding.conf > agg.best.conf)
                    || (finding.crit == agg.best.crit
                        && finding.conf == agg.best.conf
                        && finding.id < agg.best.id);

                if should_replace {
                    agg.best = finding.clone();
                }
            }
        }
    }

    // Convert aggregated findings to Finding structs with directory as ID
    let mut result: Vec<Finding> = aggregated
        .into_values()
        .map(|agg| {
            let mut result = agg.best;
            result.id = agg.directory;
            result.trait_refs = agg.matched_traits;
            result
        })
        .collect();

    // Add internal findings (not aggregated) to the result
    result.extend(internal_findings);
    result
}

/// Get risk indicator based on criticality
#[allow(dead_code)] // Used by binary target
fn risk_indicator(crit: &Criticality) -> colored::ColoredString {
    use crate::theme;
    match crit {
        Criticality::Filtered => "   ".normal(),
        Criticality::Component => "  ·".dimmed(),
        Criticality::Baseline => theme::paint_baseline("  •"),
        Criticality::Notable => theme::paint_notable("  •"),
        Criticality::Suspicious => theme::paint_suspicious(" ••"),
        Criticality::Hostile => theme::paint_hostile("•••"),
    }
}

/// Get risk level name
/// Split trait ID into namespace and rest, skipping "cap"/"obj" prefixes
/// e.g., "micro-behaviors/execution/command/subprocess" -> ("exec", "command/subprocess")
/// e.g., "objectives/anti-analysis/debugger/detect" -> ("anti-analysis", "debugger/detect")
/// e.g., "intel/discover/process/getuid" -> ("intel", "discover/process/getuid")
#[allow(dead_code)] // Used by binary target
fn split_trait_id(id: &str) -> (String, String) {
    let parts: Vec<&str> = id.split('/').collect();

    // Skip "cap" or "obj" prefix if present
    let start_idx = if parts.len() > 1 && (parts[0] == "cap" || parts[0] == "obj") {
        1
    } else {
        0
    };

    if parts.len() > start_idx + 1 {
        (
            parts[start_idx].to_string(),
            parts[start_idx + 1..].join("/"),
        )
    } else if parts.len() > start_idx {
        (parts[start_idx].to_string(), parts[start_idx].to_string())
    } else {
        (id.to_string(), id.to_string())
    }
}

/// Namespace categories for grouping findings
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[allow(dead_code)] // Used by binary target
enum Namespace {
    WellKnown,
    Objectives,
    MicroBehaviors,
    Metadata,
    ThirdParty,
}

impl Namespace {
    /// Parse namespace from trait ID prefix
    fn from_trait_id(id: &str) -> Option<Self> {
        let prefix = id.split('/').next()?;
        match prefix {
            "well-known" => Some(Self::WellKnown),
            "objectives" => Some(Self::Objectives),
            "micro-behaviors" => Some(Self::MicroBehaviors),
            "metadata" => Some(Self::Metadata),
            "third_party" | "third-party" => Some(Self::ThirdParty),
            _ => None,
        }
    }

    /// Display name for section header
    fn display_name(&self) -> &'static str {
        match self {
            Self::WellKnown => "WELL-KNOWN",
            Self::Objectives => "OBJECTIVES",
            Self::MicroBehaviors => "MICRO-BEHAVIORS",
            Self::Metadata => "METADATA",
            Self::ThirdParty => "THIRD-PARTY",
        }
    }
}

/// Get sort order for namespace (fixed order: well-known, objectives, micro-behaviors, metadata, third-party)
#[allow(dead_code)] // Used by binary target
fn namespace_sort_order(ns: &str) -> u8 {
    match ns {
        "well-known" => 0,
        "objectives" => 1,
        "micro-behaviors" => 2,
        "metadata" => 3,
        "third-party" | "third_party" => 4,
        _ => 5, // Unknown namespaces go last
    }
}

/// Convert namespace to long name, capitalizing if no explicit mapping exists
#[allow(dead_code)] // Used by binary target
fn namespace_long_name(ns: &str) -> String {
    let mapped = match ns {
        "c2" => Some("COMMAND & CONTROL"),
        "crypto" => Some("CRYPTOGRAPHY"),
        "exfil" => Some("EXFILTRATION"),
        "exec" => Some("EXECUTION"),
        "fs" => Some("FILESYSTEM"),
        "hw" => Some("HARDWARE"),
        "comm" => Some("COMMUNICATION"),
        "os" => Some("OS"),
        "anti-analysis" => Some("ANTI-ANALYSIS"),
        "anti-static" => Some("STATIC EVASION"),
        "anti-forensics" => Some("ANTI-FORENSICS"),
        "privilege-escalation" => Some("PRIVILEGE ESCALATION"),
        "process" => Some("PROCESS"),
        "mem" => Some("MEMORY"),
        "data" => Some("DATA"),
        "impact" => Some("IMPACT"),
        "credential-access" => Some("CREDENTIALS"),
        "lateral" => Some("LATERAL MOVEMENT"),
        "persist" => Some("PERSISTENCE"),
        "discovery" => Some("DISCOVERY"),
        "exploit" => Some("EXPLOIT"),
        "collect" => Some("COLLECTION"),
        "graphics" => Some("GRAPHICS"),
        "interop" => Some("INTEROPERABILITY"),
        "io" => Some("INPUT/OUTPUT"),
        "time" => Some("TIME"),
        "ui" => Some("USER INTERFACE"),
        "meta" => Some("METADATA"),
        _ => None,
    };

    match mapped {
        Some(name) => name.to_string(),
        None => {
            // Full uppercase and replace hyphens with spaces for unknown namespaces
            ns.replace('-', " ").to_uppercase()
        }
    }
}

/// Format evidence string (minimal, deduplicated)
/// Maximum width for evidence display (truncate if longer)
#[allow(dead_code)] // Used by binary target
const EVIDENCE_MAX_WIDTH: usize = 80;

/// Make descriptions more terse by removing redundant explanatory parentheticals
#[allow(dead_code)] // Used by binary target
fn terse_description(desc: &str) -> String {
    // Remove common verbose patterns that are redundant given the context
    desc.replace(" (timing attacks or sandbox detection)", "")
        .replace(" (C2 communication pattern)", "")
        .replace(" (comprehensive stealer)", "")
        .replace(" (monolithic multicall binary)", "")
        .replace(" (packer pattern)", "")
        .replace(" (potential stealer)", "")
        .replace(" (potential keylogger)", "")
        .replace(" (hardcoded alphabet + decode table)", "")
        .replace(" reveals directory contents", "")
        .replace(" (opendir + readdir + stat)", "")
        .replace(".DS_Store ", "")
        .replace(" (excluding known legitimate)", "")
        .trim()
        .to_string()
}

#[allow(dead_code)] // Used by binary target
fn format_evidence(finding: &Finding) -> String {
    // Dedupe values, drop blank/whitespace-only lines from each. If any
    // value spans multiple lines after cleaning, return the full set as a
    // newline-separated block (the renderer indents continuation lines to
    // the evidence column). Otherwise comma-join for compactness.
    let mut seen = std::collections::HashSet::new();
    let values: Vec<String> = finding
        .evidence
        .iter()
        .filter_map(|e| {
            let cleaned: String = e
                .value
                .lines()
                .filter(|l| !l.trim().is_empty())
                .collect::<Vec<_>>()
                .join("\n");
            if cleaned.is_empty() {
                return None;
            }
            if seen.insert(cleaned.clone()) {
                Some(cleaned)
            } else {
                None
            }
        })
        .take(5)
        .collect();

    if values.is_empty() {
        return String::new();
    }

    if values.iter().any(|v| v.contains('\n')) {
        values.join("\n")
    } else {
        values.join(", ")
    }
}

// =============================================================================
// JSONL (Newline-Delimited JSON) Output for Streaming
// =============================================================================

/// JSONL file entry - emitted for each file as it's analyzed
#[allow(dead_code)] // Used by binary target
#[derive(serde::Serialize)]
struct JsonlFileEntry<'a> {
    #[serde(rename = "type")]
    entry_type: &'static str,
    #[serde(flatten)]
    file: &'a crate::types::FileAnalysis,
}

/// JSONL summary entry - emitted at the end of streaming output
#[allow(dead_code)] // Used by binary target
#[derive(serde::Serialize)]
struct JsonlSummary {
    #[serde(rename = "type")]
    entry_type: &'static str,
    files_analyzed: u32,
    #[serde(rename = "x")]
    score: u32,
    hostile: u32,
    suspicious: u32,
    notable: u32,
    duration_ms: u64,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    tools: Vec<String>,
}

/// Filter findings for formula generation.
/// Aggregates by directory and removes baseline/low-confidence findings.
#[allow(dead_code)] // Used by binary target
fn filter_findings_for_formula(findings: &[Finding]) -> Vec<Finding> {
    let aggregated = aggregate_findings_by_directory(findings);
    aggregated
        .into_iter()
        .filter(|f| f.crit != Criticality::Baseline && f.conf >= 0.5)
        .collect()
}

/// Format a single file analysis as a JSONL line
#[allow(dead_code)] // Used by binary target
pub(crate) fn format_jsonl_line(file: &crate::types::FileAnalysis) -> Result<String> {
    // Compute formula if not already set
    if file.formula.is_none() {
        let mut file_with_formula = file.clone();
        let filtered = filter_findings_for_formula(&file.findings);
        let formula = malecule_bridge::formula_from_findings(&filtered);
        file_with_formula.formula = Some(if formula.is_empty() {
            "∅".to_string()
        } else {
            formula
        });
        let entry = JsonlFileEntry {
            entry_type: "file",
            file: &file_with_formula,
        };
        return Ok(serde_json::to_string(&entry)?);
    }

    let entry = JsonlFileEntry {
        entry_type: "file",
        file,
    };
    Ok(serde_json::to_string(&entry)?)
}

/// Format the summary as a JSONL line (for end of streaming output)
#[allow(dead_code)] // Used by binary target
pub(crate) fn format_jsonl_summary(report: &AnalysisReport) -> Result<String> {
    let summary = report.summary.as_ref();
    let counts = summary.map(|s| &s.counts);

    let entry = JsonlSummary {
        entry_type: "summary",
        files_analyzed: summary
            .map(|s| s.files_analyzed)
            .unwrap_or(report.files.len() as u32),
        score: summary.map(|s| s.score).unwrap_or(0),
        hostile: counts.map(|c| c.hostile).unwrap_or(0),
        suspicious: counts.map(|c| c.suspicious).unwrap_or(0),
        notable: counts.map(|c| c.notable).unwrap_or(0),
        duration_ms: summary
            .map(|s| s.duration_ms)
            .unwrap_or(report.metadata.analysis_duration_ms),
        tools: summary
            .map(|s| s.tools.clone())
            .unwrap_or_else(|| report.metadata.tools_used.clone()),
    };
    Ok(serde_json::to_string(&entry)?)
}

/// Format entire report as JSONL (for non-streaming output)
#[allow(dead_code)] // Used by binary target
pub(crate) fn format_jsonl(report: &AnalysisReport) -> Result<String> {
    let mut lines = Vec::with_capacity(report.files.len() + 1);

    // Emit each file as a line
    for file in &report.files {
        lines.push(format_jsonl_line(file)?);
    }

    // Emit summary at end
    lines.push(format_jsonl_summary(report)?);

    // Join with newlines and add trailing newline for proper JSONL streaming
    Ok(format!("{}\n", lines.join("\n")))
}

/// Format report as compact text for small LLMs.
///
/// Output format:
/// ```text
/// # tiny-v2 fields are tab-separated
/// # @ path type size score
/// # H|S|N|B|C|F id desc evidence
/// @	path/to/file.exe	elf	1.2MB	142
/// H	command-and-control/c2-beacon	C2 beacon pattern	hardcoded_ip_callback
/// S	crypto/custom-encryption	Custom encryption loop	XOR_0x5a_loop
/// N	net/socket	Network socket usage	connect
/// ```
///
/// One line per finding, sorted by criticality (highest first).
/// Evidence is truncated to 48 chars. Files with no findings are omitted.
#[allow(dead_code, clippy::tabs_in_doc_comments)] // Used by binary target; tabs in example are intentional (tab-separated format)
pub(crate) fn format_tiny(report: &AnalysisReport) -> String {
    // Check if any file has findings worth showing before emitting the header.
    let has_visible_findings = report
        .files
        .iter()
        .any(|file| file.findings.iter().any(|f| tiny_should_show(f, file)));
    if !has_visible_findings {
        return String::new();
    }

    let mut out = String::with_capacity(4096);
    out.push_str(
        "# tiny-v2: tab-separated; @ path type size score; H/S/N/B/C/F id desc evidence\n",
    );
    if let Some(summary) = &report.summary {
        out.push_str(&format!("# score\t{}\n", summary.score));
    }

    for file in &report.files {
        // Include baseline and matched composites, but keep component findings
        // only when a matched composite references them. Deduplicate by trait ID
        // and merge a small evidence set to keep LLM context compact.
        let mut findings = tiny_findings(file);

        if findings.is_empty() {
            continue;
        }

        // Sort by criticality descending, then by id for stability
        findings.sort_unstable_by(|a, b| b.crit.cmp(&a.crit).then_with(|| a.id.cmp(&b.id)));

        // File header: @ <path> <type> <size> <score>
        let size = format_size(file.size);
        out.push_str("@\t");
        out.push_str(&tiny_field(&file.path));
        out.push('\t');
        out.push_str(&tiny_field(&file.file_type));
        out.push('\t');
        out.push_str(&size);
        out.push('\t');
        out.push_str(&file.score.to_string());
        out.push('\n');

        for f in &findings {
            let letter = match f.crit {
                Criticality::Hostile => 'H',
                Criticality::Suspicious => 'S',
                Criticality::Notable => 'N',
                Criticality::Baseline => 'B',
                Criticality::Component => 'C',
                Criticality::Filtered => 'F',
            };
            out.push(letter);
            out.push('\t');
            out.push_str(&tiny_field(&f.id));
            out.push('\t');
            out.push_str(&tiny_field(&terse_description(&f.desc)));
            out.push('\t');
            out.push_str(&f.evidence);
            out.push('\n');
        }
    }

    out
}

fn tiny_field(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[derive(Clone)]
struct TinyFinding {
    id: String,
    desc: String,
    crit: Criticality,
    evidence: String,
}

fn tiny_findings(file: &FileAnalysis) -> Vec<TinyFinding> {
    let mut by_id: HashMap<&str, TinyFinding> = HashMap::new();
    let mut order: Vec<&str> = Vec::new();

    for finding in file.findings.iter().filter(|f| tiny_should_show(f, file)) {
        if let Some(existing) = by_id.get_mut(finding.id.as_str()) {
            if finding.crit > existing.crit {
                existing.crit = finding.crit;
            }
            existing.evidence = tiny_merged_evidence(&existing.evidence, finding);
            continue;
        }

        order.push(finding.id.as_str());
        by_id.insert(
            finding.id.as_str(),
            TinyFinding {
                id: finding.id.clone(),
                desc: finding.desc.clone(),
                crit: finding.crit,
                evidence: tiny_evidence(finding),
            },
        );
    }

    order
        .into_iter()
        .filter_map(|id| by_id.remove(id))
        .collect()
}

fn tiny_should_show(finding: &Finding, file: &FileAnalysis) -> bool {
    if finding.crit != Criticality::Component {
        return true;
    }

    file.findings
        .iter()
        .any(|f| f.trait_refs.iter().any(|id| id == &finding.id))
}

fn tiny_evidence(finding: &Finding) -> String {
    let mut seen = HashSet::new();
    finding
        .evidence
        .iter()
        .filter_map(|ev| {
            let value = tiny_field(ev.value.trim());
            if value.is_empty() {
                return None;
            }
            let value = truncate_tiny_field(&value, 48);
            seen.insert(value.clone()).then_some(value)
        })
        .take(3)
        .collect::<Vec<_>>()
        .join(",")
}

fn tiny_merged_evidence(existing: &str, finding: &Finding) -> String {
    let mut values: Vec<String> = existing
        .split(',')
        .filter(|value| !value.is_empty())
        .map(ToOwned::to_owned)
        .collect();
    let mut seen: HashSet<String> = values.iter().cloned().collect();

    for value in tiny_evidence(finding)
        .split(',')
        .filter(|value| !value.is_empty())
        .map(ToOwned::to_owned)
    {
        if seen.insert(value.clone()) {
            values.push(value);
        }
        if values.len() >= 3 {
            break;
        }
    }

    values.join(",")
}

fn truncate_tiny_field(value: &str, max_chars: usize) -> String {
    if value.chars().count() <= max_chars {
        return value.to_string();
    }

    let keep = max_chars.saturating_sub(3);
    let mut truncated: String = value.chars().take(keep).collect();
    truncated.push_str("...");
    truncated
}

/// Format byte size as human-readable string (compact)
fn format_size(bytes: u64) -> String {
    if bytes == 0 {
        return String::new();
    }
    const KB: u64 = 1024;
    const MB: u64 = 1024 * KB;
    const GB: u64 = 1024 * MB;
    if bytes >= GB {
        format!("{:.1}GB", bytes as f64 / GB as f64)
    } else if bytes >= MB {
        format!("{:.1}MB", bytes as f64 / MB as f64)
    } else if bytes >= KB {
        format!("{}KB", bytes / KB)
    } else {
        format!("{}B", bytes)
    }
}

/// Parse JSONL (newline-delimited JSON) back to AnalysisReport
#[allow(dead_code)] // Used by binary target
pub(crate) fn parse_jsonl(jsonl: &str) -> Result<AnalysisReport> {
    let mut files = Vec::new();
    let mut summary = None;
    let mut version = "3".to_string();

    // Parse each line as a JSON entry
    for line in jsonl.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }

        let value: serde_json::Value = serde_json::from_str(trimmed)?;
        let entry_type = value.get("type").and_then(|v| v.as_str());

        match entry_type {
            Some("file") => {
                let file: crate::types::FileAnalysis = serde_json::from_value(value)?;
                files.push(file);
            }
            Some("summary") => {
                if let Some(v) = value
                    .get("version")
                    .or_else(|| value.get("schema_version"))
                    .and_then(|v| v.as_str())
                {
                    version = v.to_string();
                }
                let tools: Vec<String> = value
                    .get("tools")
                    .or_else(|| value.get("tools_used"))
                    .and_then(|v| v.as_array())
                    .map(|arr| {
                        arr.iter()
                            .filter_map(|v| v.as_str().map(str::to_string))
                            .collect()
                    })
                    .unwrap_or_default();
                let errors: Vec<String> = value
                    .get("errors")
                    .and_then(|v| v.as_array())
                    .map(|arr| {
                        arr.iter()
                            .filter_map(|v| v.as_str().map(str::to_string))
                            .collect()
                    })
                    .unwrap_or_default();
                let duration_ms = value
                    .get("duration_ms")
                    .or_else(|| value.get("analysis_duration_ms"))
                    .and_then(serde_json::Value::as_u64)
                    .unwrap_or(0);

                summary = Some(crate::types::ReportSummary {
                    files_analyzed: value
                        .get("files_analyzed")
                        .and_then(serde_json::Value::as_u64)
                        .unwrap_or(files.len() as u64) as u32,
                    counts: crate::types::FindingCounts {
                        hostile: value
                            .get("hostile")
                            .and_then(serde_json::Value::as_u64)
                            .unwrap_or(0) as u32,
                        suspicious: value
                            .get("suspicious")
                            .and_then(serde_json::Value::as_u64)
                            .unwrap_or(0) as u32,
                        notable: value
                            .get("notable")
                            .and_then(serde_json::Value::as_u64)
                            .unwrap_or(0) as u32,
                    },
                    score: 0,
                    duration_ms,
                    tools,
                    errors,
                });
            }
            _ => {
                // Unknown entry type, skip
            }
        }
    }

    // Create a minimal AnalysisReport with the parsed data
    let target = if let Some(first_file) = files.first() {
        crate::types::TargetInfo {
            path: first_file.path.clone(),
            file_type: first_file.file_type.clone(),
            sha256: first_file.sha256.clone(),
            size_bytes: first_file.size,
            architectures: None,
        }
    } else {
        crate::types::TargetInfo {
            path: "unknown".to_string(),
            file_type: "unknown".to_string(),
            sha256: String::new(),
            size_bytes: 0,
            architectures: None,
        }
    };

    let mut report = AnalysisReport::new(target);
    report.version = version;
    report.files = files;
    report.summary = summary;

    Ok(report)
}

/// Get terminal width, defaulting to 100 if unavailable
#[allow(dead_code)] // Used by binary target
fn terminal_width() -> usize {
    terminal_size::terminal_size()
        .map(|(w, _)| w.0 as usize)
        .unwrap_or(100)
}

/// Truncate string to max width, using ellipsis (…) if needed
#[allow(dead_code)] // Used by binary target
fn truncate_with_ellipsis(s: &str, max_width: usize) -> String {
    if s.len() <= max_width {
        return s.to_string();
    }
    if max_width <= 1 {
        return "…".to_string();
    }
    // Find char boundary for truncation
    let mut end = max_width - 1;
    while !s.is_char_boundary(end) && end > 0 {
        end -= 1;
    }
    format!("{}…", &s[..end])
}

fn display_file_type(file_type: &str) -> String {
    file_type.to_uppercase()
}

/// Render a section label as a muted 256-color pill — bold white on dark bg.
/// Hue encodes the namespace: red=well-known, magenta=objectives, blue=behaviors, gray=metadata.
#[allow(dead_code)] // Used by binary target
fn section_pill(ns: &Namespace) -> colored::ColoredString {
    let (name, r, g, b) = match ns {
        Namespace::WellKnown => (ns.display_name(), 95, 0, 0), // dark red (256 idx 52)
        Namespace::Objectives => (ns.display_name(), 95, 0, 95), // dark magenta (53)
        Namespace::MicroBehaviors => (ns.display_name(), 0, 0, 95), // dark blue (17)
        Namespace::Metadata => (ns.display_name(), 48, 48, 48), // dark gray (236)
        Namespace::ThirdParty => (ns.display_name(), 120, 56, 0), // dark orange
    };
    format!(" {name} ").bold().white().on_truecolor(r, g, b)
}

/// Full-width slate-blue rule used as a file-boundary marker. Routed
/// through `theme::paint_rule` and `theme::RULE_CHAR` so analyze and
/// diff share the exact same separator.
#[allow(dead_code)] // Used by binary target
fn file_rule(width: usize) -> colored::ColoredString {
    let rule: String = crate::theme::RULE_CHAR.to_string().repeat(width);
    crate::theme::paint_rule(rule)
}

/// Bullet indicator based on criticality: • notable, •• suspicious, ••• hostile
#[allow(dead_code)] // Used by binary target
fn bullet_for_crit(crit: &Criticality) -> colored::ColoredString {
    use crate::theme;
    match crit {
        Criticality::Hostile => theme::paint_hostile("•••"),
        Criticality::Suspicious => theme::paint_suspicious(" ••"),
        _ => theme::paint_baseline("  •"),
    }
}

/// Colorize text based on criticality.
#[allow(dead_code)] // Used by binary target
fn colorize_by_crit(text: &str, crit: &Criticality) -> colored::ColoredString {
    use crate::theme;
    match crit {
        Criticality::Hostile => theme::paint_hostile(text),
        Criticality::Suspicious => theme::paint_suspicious(text),
        _ => theme::paint_baseline(text),
    }
}

/// Extract short trait ID (strip namespace prefix)
/// e.g., "well-known/malware/BPFDoor" -> "BPFDoor"
/// e.g., "objectives/c2/http/beacon" -> "c2/http/beacon"
/// e.g., "micro-behaviors/fs/read/file" -> "fs/read/file"
#[allow(dead_code)] // Used by binary target
fn short_trait_id(id: &str) -> String {
    let parts: Vec<&str> = id.split('/').collect();
    if parts.len() > 1 {
        // Skip namespace prefix (well-known, objectives, micro-behaviors)
        let first = parts[0];
        if first == "well-known"
            || first == "objectives"
            || first == "micro-behaviors"
            || first == "third_party"
            || first == "third-party"
        {
            return parts[1..].join("/");
        }
    }
    id.to_string()
}

/// Format analysis report for terminal display
/// Uses the v2 flat files array structure.
#[allow(dead_code)] // Used by binary target
pub(crate) fn format_terminal(report: &AnalysisReport) -> String {
    let mut output = String::new();
    let term_width = terminal_width();

    // Iterate over files that have findings
    for file in &report.files {
        // Skip files with no findings
        if file.findings.is_empty() {
            continue;
        }

        // Per RULES.md: components are hidden from terminal output unless a
        // matched composite that references them fires. Build the set of
        // component IDs referenced by notable-or-higher composites, then keep
        // components only when they appear in that set.
        let referenced_component_ids: HashSet<&str> = file
            .findings
            .iter()
            .filter(|f| f.crit >= Criticality::Notable && f.conf >= 0.5)
            .flat_map(|f| f.trait_refs.iter().map(String::as_str))
            .collect();

        let pre_filtered: Vec<Finding> = file
            .findings
            .iter()
            .filter(|f| f.conf >= 0.5)
            .filter(|f| {
                f.crit >= Criticality::Notable
                    || (f.crit == Criticality::Component
                        && referenced_component_ids.contains(f.id.as_str()))
            })
            .cloned()
            .collect();

        // Aggregate remaining findings by directory path
        let filtered = aggregate_findings_by_directory(&pre_filtered);

        if filtered.is_empty() {
            continue;
        }

        // Group findings by namespace
        let mut by_namespace: HashMap<Namespace, Vec<&Finding>> = HashMap::new();
        for finding in &filtered {
            if let Some(ns) = Namespace::from_trait_id(&finding.id) {
                by_namespace.entry(ns).or_default().push(finding);
            }
        }

        // Sort findings within each namespace by criticality (hostile first)
        for findings in by_namespace.values_mut() {
            findings.sort_unstable_by(|a, b| b.crit.cmp(&a.crit).then_with(|| a.id.cmp(&b.id)));
        }

        // Pre-calculate column widths across ALL findings in this file
        let all_findings: Vec<&&Finding> = by_namespace.values().flat_map(|v| v.iter()).collect();

        let trait_width = all_findings
            .iter()
            .map(|f| short_trait_id(&f.id).len())
            .max()
            .unwrap_or(20);

        let natural_desc_width = all_findings
            .iter()
            .map(|f| terse_description(&f.desc).len())
            .max()
            .unwrap_or(30);

        // Reserve at least MIN_EVIDENCE_WIDTH columns for evidence by capping the
        // description column. One overly long description would otherwise push
        // evidence off the screen, leaving every row with just a stray `…`.
        // Layout overhead: bullet(3) + space(1) + trait + 2 spaces + 2 spaces = 8 + trait_width
        // 24 cols accommodates two short kv-array members like
        // `[lzma_crc32, lzma_crc64]` — descriptions truncate hard
        // first since they're often paraphrasable from the trait id.
        const MIN_EVIDENCE_WIDTH: usize = 24;
        let overhead = 8 + trait_width;
        let max_desc_width = term_width.saturating_sub(overhead + MIN_EVIDENCE_WIDTH);
        let desc_width = natural_desc_width.min(max_desc_width);

        let evidence_width = term_width.saturating_sub(overhead + desc_width);

        // Generate formula from filtered findings
        let formula = malecule_bridge::formula_from_findings(&filtered);

        let file_type_display = display_file_type(&file.file_type);

        // File header: [indent] path  type • formula
        let type_formula = if formula.is_empty() {
            file_type_display
        } else {
            format!("{} • {}", file_type_display, formula)
        };

        // Indent nested files (archive members, embedded binaries, decoded payloads)
        let indent = "  ".repeat(file.depth as usize);
        // Strip virtual path prefixes (!!member, ##encoding) for display if depth > 0
        let display_path = if file.depth > 0 {
            file.path
                .rsplit(crate::types::file_analysis::ARCHIVE_DELIMITER)
                .next()
                .or_else(|| {
                    file.path
                        .rsplit(crate::types::file_analysis::ENCODING_DELIMITER)
                        .next()
                })
                .unwrap_or(&file.path)
        } else {
            &file.path
        };

        output.push_str(&format!(
            "{}{}  {}\n",
            indent,
            display_path.bright_white().bold(),
            type_formula.bright_black()
        ));
        let rule_width = term_width.saturating_sub(indent.len());
        output.push_str(&format!("{}{}\n", indent, file_rule(rule_width)));

        // Render namespaces in fixed order: WELL-KNOWN, OBJECTIVES, MICRO-BEHAVIORS, METADATA, THIRD-PARTY.
        // First section follows the file rule with no gap; later sections get a leading blank.
        let mut first_section = true;
        for ns in [
            Namespace::WellKnown,
            Namespace::Objectives,
            Namespace::MicroBehaviors,
            Namespace::Metadata,
            Namespace::ThirdParty,
        ] {
            let Some(findings) = by_namespace.get(&ns) else {
                continue; // Skip empty sections
            };

            if !first_section {
                output.push('\n');
            }
            first_section = false;

            output.push_str(&format!("{}\n", section_pill(&ns)));

            // Bullet (3) + space (1) + trait + 2 spaces + desc + 2 spaces.
            // Continuation lines for multi-line evidence start at this column.
            let evidence_col = 3 + 1 + trait_width + 2 + desc_width + 2;
            let evidence_indent = " ".repeat(evidence_col);
            // Cap multi-line evidence so a single huge match doesn't drown
            // the rest of the output. Beyond the cap, the last visible line
            // gets a trailing ellipsis.
            const MAX_EVIDENCE_LINES: usize = 4;

            // Render each finding
            for finding in findings {
                let trait_id = short_trait_id(&finding.id);
                let desc = terse_description(&finding.desc);
                let evidence = format_evidence(finding);

                // Build the line with proper column alignment
                // Format: ● trait_id  description  evidence
                let bullet = bullet_for_crit(&finding.crit);
                let padded_trait = format!("{:width$}", trait_id, width = trait_width);
                let truncated_desc = truncate_with_ellipsis(&desc, desc_width);
                let padded_desc = format!("{:width$}", truncated_desc, width = desc_width);

                let raw_lines: Vec<&str> = evidence.lines().collect();
                let (visible_lines, overflow) = if raw_lines.len() > MAX_EVIDENCE_LINES {
                    (&raw_lines[..MAX_EVIDENCE_LINES], true)
                } else {
                    (&raw_lines[..], false)
                };

                if visible_lines.is_empty() {
                    output.push_str(&format!(
                        "{} {}  {}\n",
                        bullet,
                        padded_trait,
                        colorize_by_crit("", &finding.crit)
                    ));
                    continue;
                }

                for (i, line) in visible_lines.iter().enumerate() {
                    let truncated = truncate_with_ellipsis(line, evidence_width);
                    let colored = colorize_by_crit(&truncated, &finding.crit);

                    if i == 0 {
                        output.push_str(&format!(
                            "{} {}  {}  {}\n",
                            bullet, padded_trait, padded_desc, colored
                        ));
                    } else {
                        output.push_str(&format!("{}{}\n", evidence_indent, colored));
                    }
                }
                // Overflow indicator on its own line: dimmed `…` at the
                // evidence column. Unambiguous "more lines below were
                // dropped" without doubling up with per-line truncation
                // ellipses.
                if overflow {
                    output.push_str(&format!(
                        "{}{}\n",
                        evidence_indent,
                        colorize_by_crit("…", &finding.crit)
                    ));
                }
            }
        }

        // Trailing blank after all sections separates this file from the next.
        output.push('\n');
    }

    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{AnalysisReport, Evidence, FindingKind, TargetInfo, YaraMatch};
    use chrono::Utc;

    fn create_test_report(findings: Vec<Finding>, yara_matches: Vec<YaraMatch>) -> AnalysisReport {
        let mut report = AnalysisReport {
            version: "2.0".to_string(),
            analysis_timestamp: Some(Utc::now()),
            target: TargetInfo {
                path: "/test/sample.bin".to_string(),
                file_type: "ELF".to_string(),
                size_bytes: 12345,
                sha256: "def456abc".to_string(),
                architectures: Some(vec!["x86_64".to_string()]),
            },
            findings,
            traits: vec![],
            structure: vec![],
            functions: vec![],
            strings: vec![],
            sections: vec![],
            imports: vec![],
            exports: vec![],
            yara_matches,
            syscalls: vec![],
            binary_properties: None,
            code_metrics: None,
            source_code_metrics: None,
            overlay_metrics: None,
            metrics: None,
            kv_tree: None,
            paths: vec![],
            directories: vec![],
            env_vars: vec![],
            archive_contents: vec![],
            scanned_path: None,
            files: vec![],
            summary: None,
            metadata: crate::types::AnalysisMetadata {
                analysis_duration_ms: 100,
                tools_used: vec!["test".to_string()],
                errors: vec![],
            },
            diff: None,
        };
        // Finalize to populate files array
        report.finalize();
        report
    }

    #[test]
    fn test_aggregate_findings_empty() {
        let findings: Vec<Finding> = vec![];
        let aggregated = aggregate_findings_by_directory(&findings);
        assert_eq!(aggregated.len(), 0);
    }

    #[test]
    fn test_aggregate_findings_different_directories() {
        let findings = vec![
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "execution/shell::bash-variant".to_string(),
                desc: "Execute bash".to_string(),
                conf: 0.9,
                crit: Criticality::Hostile,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "net/http::get-variant".to_string(),
                desc: "HTTP GET request".to_string(),
                conf: 0.8,
                crit: Criticality::Suspicious,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
        ];
        let aggregated = aggregate_findings_by_directory(&findings);
        assert_eq!(aggregated.len(), 2);
        // IDs should be base trait IDs (without ::variant suffix)
        let ids: Vec<_> = aggregated.iter().map(|f| f.id.as_str()).collect();
        assert!(ids.contains(&"execution/shell"));
        assert!(ids.contains(&"net/http"));
    }

    #[test]
    fn test_aggregate_findings_same_directory_keeps_highest_criticality() {
        let findings = vec![
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "execution/shell::bash-variant".to_string(),
                desc: "Execute bash".to_string(),
                conf: 0.7,
                crit: Criticality::Suspicious,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "execution/shell::sh-variant".to_string(),
                desc: "Execute sh".to_string(),
                conf: 0.7,
                crit: Criticality::Hostile,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
        ];
        let aggregated = aggregate_findings_by_directory(&findings);
        assert_eq!(aggregated.len(), 1);
        assert_eq!(aggregated[0].id, "execution/shell");
        assert_eq!(aggregated[0].crit, Criticality::Hostile);
        // Should have both trait IDs in trait_refs
        assert_eq!(aggregated[0].trait_refs.len(), 2);
    }

    #[test]
    fn test_aggregate_findings_same_directory_keeps_highest_confidence() {
        let findings = vec![
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "execution/shell::bash-variant".to_string(),
                desc: "Execute bash".to_string(),
                conf: 0.6,
                crit: Criticality::Hostile,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "execution/shell::sh-variant".to_string(),
                desc: "Execute sh".to_string(),
                conf: 0.9,
                crit: Criticality::Hostile,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
        ];
        let aggregated = aggregate_findings_by_directory(&findings);
        assert_eq!(aggregated.len(), 1);
        assert_eq!(aggregated[0].id, "execution/shell");
        assert_eq!(aggregated[0].conf, 0.9);
    }

    #[test]
    fn test_risk_indicator() {
        // Verify the underlying text content (colored strings deref to &str)
        assert_eq!(&*risk_indicator(&Criticality::Baseline), "  •");
        assert_eq!(&*risk_indicator(&Criticality::Notable), "  •");
        assert_eq!(&*risk_indicator(&Criticality::Suspicious), " ••");
        assert_eq!(&*risk_indicator(&Criticality::Hostile), "•••");
    }

    #[test]
    fn test_split_trait_id() {
        let (ns, rest) = split_trait_id("intel/discover/process");
        assert_eq!(ns, "intel");
        assert_eq!(rest, "discover/process");
    }

    #[test]
    fn test_split_trait_id_no_namespace() {
        let (ns, rest) = split_trait_id("test");
        assert_eq!(ns, "test");
        assert_eq!(rest, "test");
    }

    #[test]
    fn test_namespace_long_name() {
        assert_eq!(namespace_long_name("c2"), "COMMAND & CONTROL");
        assert_eq!(namespace_long_name("discovery"), "DISCOVERY");
        assert_eq!(namespace_long_name("crypto"), "CRYPTOGRAPHY");
        assert_eq!(namespace_long_name("credential-access"), "CREDENTIALS");
        assert_eq!(namespace_long_name("anti-static"), "STATIC EVASION");
        assert_eq!(namespace_long_name("comm"), "COMMUNICATION");
        assert_eq!(namespace_long_name("collect"), "COLLECTION");
        assert_eq!(namespace_long_name("impact"), "IMPACT");
        assert_eq!(namespace_long_name("meta"), "METADATA");
        assert_eq!(namespace_long_name("unknown"), "UNKNOWN");
    }

    #[test]
    fn test_format_evidence_empty() {
        let trait_item = Finding {
            kind: FindingKind::Capability,
            trait_refs: vec![],
            id: "test".to_string(),
            desc: "Test trait".to_string(),
            conf: 0.8,
            crit: Criticality::Notable,
            mbc: None,
            attack: None,
            evidence: vec![],
            match_count: 0,
            source_file: None,
        };
        assert_eq!(format_evidence(&trait_item), "");
    }

    #[test]
    fn test_format_evidence_with_values() {
        let trait_item = Finding {
            kind: FindingKind::Capability,
            trait_refs: vec![],
            id: "test".to_string(),
            desc: "Test".to_string(),
            conf: 0.8,
            crit: Criticality::Notable,
            mbc: None,
            attack: None,
            evidence: vec![
                Evidence {
                    method: "yara".to_string(),
                    source: "test".to_string(),
                    value: "cmd.exe".to_string(),
                    location: None,
                    ..Default::default()
                },
                Evidence {
                    method: "yara".to_string(),
                    source: "test".to_string(),
                    value: "powershell".to_string(),
                    location: None,
                    ..Default::default()
                },
            ],
            match_count: 2,
            source_file: None,
        };
        let formatted = format_evidence(&trait_item);
        assert!(formatted.contains("cmd.exe"));
        assert!(formatted.contains("powershell"));
    }

    #[test]
    fn test_format_terminal_empty_report() {
        let report = create_test_report(vec![], vec![]);
        let output = format_terminal(&report);
        assert!(output.is_empty());
    }

    #[test]
    fn test_format_terminal_with_capabilities() {
        let capabilities = vec![Finding {
            kind: FindingKind::Capability,
            trait_refs: vec![],
            id: "micro-behaviors/execution/shell".to_string(),
            desc: "Execute shell commands".to_string(),
            conf: 0.9,
            crit: Criticality::Hostile,
            mbc: None,
            attack: None,
            evidence: vec![],
            match_count: 0,
            source_file: None,
        }];
        let report = create_test_report(capabilities, vec![]);
        let output = format_terminal(&report);
        assert!(output.contains("execution/shell") || output.contains("MICRO-BEHAVIORS"));
    }

    #[test]
    fn test_format_terminal_includes_third_party() {
        let findings = vec![Finding {
            kind: FindingKind::Indicator,
            trait_refs: vec![],
            id: "third_party/Sekoia/Backdoor/Lin/Bpfdoor".to_string(),
            desc: "Detect the BPFDoor backdoor".to_string(),
            conf: 0.95,
            crit: Criticality::Hostile,
            mbc: None,
            attack: None,
            evidence: vec![Evidence {
                method: "yara".to_string(),
                source: "test".to_string(),
                value: "$op1".to_string(),
                location: None,
                ..Default::default()
            }],
            match_count: 1,
            source_file: None,
        }];
        let report = create_test_report(findings, vec![]);

        let output = format_terminal(&report);

        assert!(output.contains("THIRD-PARTY"));
        assert!(output.contains("Sekoia/Backdoor/Lin/Bpfdoor"));
        assert!(!output.contains("third_party/Sekoia"));
    }

    #[test]
    fn test_format_tiny_includes_description_as_tsv_field() {
        let findings = vec![Finding {
            kind: FindingKind::Capability,
            trait_refs: vec![],
            id: "micro-behaviors/process/create/shell::bash".to_string(),
            desc: "Execute shell commands".to_string(),
            conf: 0.9,
            crit: Criticality::Notable,
            mbc: None,
            attack: None,
            evidence: vec![Evidence {
                method: "symbol".to_string(),
                source: "test".to_string(),
                value: "bash\nwith\twhitespace".to_string(),
                location: None,
                ..Default::default()
            }],
            match_count: 1,
            source_file: None,
        }];
        let report = create_test_report(findings, vec![]);

        let output = format_tiny(&report);

        assert!(output.contains("# tiny-v2"));
        assert!(output.contains("@\t/test/sample.bin\tELF\t12KB\t"));
        assert!(output.contains(
            "N\tmicro-behaviors/process/create/shell::bash\tExecute shell commands\tbash with whitespace"
        ));
    }

    #[test]
    fn test_format_tiny_includes_baseline_and_composite_findings() {
        let findings = vec![
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "micro-behaviors/fs/read::open".to_string(),
                desc: "Open file for reading".to_string(),
                conf: 0.8,
                crit: Criticality::Baseline,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "micro-behaviors/fs/read::open".to_string(),
                desc: "Open file for reading".to_string(),
                conf: 0.8,
                crit: Criticality::Baseline,
                mbc: None,
                attack: None,
                evidence: vec![Evidence {
                    method: "symbol".to_string(),
                    source: "test".to_string(),
                    value: "fopen".to_string(),
                    location: None,
                    ..Default::default()
                }],
                match_count: 0,
                source_file: None,
            },
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "objectives/execution/loader::fragment".to_string(),
                desc: "Loader fragment".to_string(),
                conf: 0.7,
                crit: Criticality::Component,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "objectives/execution/loader::unused-fragment".to_string(),
                desc: "Unused loader fragment".to_string(),
                conf: 0.7,
                crit: Criticality::Component,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![
                    "micro-behaviors/fs/read::open".to_string(),
                    "objectives/execution/loader::fragment".to_string(),
                ],
                id: "objectives/execution/loader::matched-composite".to_string(),
                desc: "Matched composite loader".to_string(),
                conf: 0.95,
                crit: Criticality::Suspicious,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
        ];
        let report = create_test_report(findings, vec![]);

        let output = format_tiny(&report);

        assert!(output.contains("B\tmicro-behaviors/fs/read::open\tOpen file for reading\t"));
        assert_eq!(
            output
                .matches("B\tmicro-behaviors/fs/read::open\tOpen file for reading\t")
                .count(),
            1
        );
        assert!(output.contains("B\tmicro-behaviors/fs/read::open\tOpen file for reading\tfopen"));
        assert!(output.contains("C\tobjectives/execution/loader::fragment\tLoader fragment\t"));
        assert!(!output.contains("objectives/execution/loader::unused-fragment"));
        assert!(output.contains(
            "S\tobjectives/execution/loader::matched-composite\tMatched composite loader\t"
        ));
    }
}
