//! Output formatting and reporting.
//!
//! This module handles formatting analysis results for different output modes:
//! - Human-readable terminal output with colors
//! - JSON output for machine consumption
//! - Summary classification for quick triage
//!
//! # Output Modes
//!
//! - Default: Human-readable with colored output
//! - `--json`: Full JSON report
//! - `--summary`: Quick classification only

#[allow(unused_imports)] // Used by binary target via format_human_single
use crate::malecule_bridge;
use crate::types::{AnalysisReport, ContextLine, Criticality, FileAnalysis, Finding, Note};
use anyhow::Result;
use colored::Colorize;
use std::collections::{HashMap, HashSet};

/// Extract base trait ID for aggregation (strip ::variant suffix)
/// e.g., "well-known/malware/trojan/macos-stealer-cpp::variant" -> "well-known/malware/trojan/macos-stealer-cpp"
/// e.g., "objectives/credential-access/stealer/shell::system-wide" -> "objectives/credential-access/stealer/shell"
/// Trait IDs without a variant suffix are returned unchanged.
#[allow(dead_code)] // Used by binary target
#[must_use]
fn get_directory_path(id: &str) -> String {
    // Strip variant suffix (::variant) if present
    // The base trait ID (without variant) is used as the aggregation key
    id.split("::").next().unwrap_or(id).to_string()
}

/// Aggregated finding for a directory path
#[allow(dead_code)] // Used by binary target
#[derive(Clone)]
struct AggregatedFinding {
    /// The directory path (e.g., "execution/command/subprocess")
    directory: String,
    /// The best (highest criticality) finding
    best: Finding,
    /// All trait IDs that matched in this directory
    matched_traits: Vec<String>,
}

/// Aggregate findings by directory path, keeping highest criticality (then highest conf)
/// Returns findings with IDs set to directory paths and trait_refs containing all matched trait IDs
/// Internal findings (from code analyzers) are not aggregated - shown individually
#[allow(dead_code)] // Used by binary target
#[must_use]
pub(crate) fn aggregate_findings_by_directory(findings: &[Finding]) -> Vec<Finding> {
    let mut aggregated: HashMap<String, AggregatedFinding> = HashMap::new();
    let mut internal_findings = Vec::new();

    for finding in findings {
        // YAML traits with variants (containing "::") are always aggregated
        // Even if they have evidence from internal sources (like symbol matching)
        let has_variant_suffix = finding.id.contains("::");

        // Check if this is an internal finding (generated by code, not from YAML traits)
        let is_internal = !has_variant_suffix
            && !finding.evidence.is_empty()
            && finding.evidence.iter().any(|e| {
                // Internal sources (generated by analyzers, not from YAML traits)
                e.source == "codesign_parser"
                    || e.source == "binary_analyzer"
                    || e.source == "strings_extractor"
                    || e.source == "import_mapper"
            });

        // Internal findings bypass aggregation - they're shown individually
        if is_internal {
            internal_findings.push(finding.clone());
            continue;
        }

        let dir_path = get_directory_path(&finding.id);

        match aggregated.get_mut(&dir_path) {
            None => {
                aggregated.insert(
                    dir_path.clone(),
                    AggregatedFinding {
                        directory: dir_path,
                        best: finding.clone(),
                        matched_traits: vec![finding.id.clone()],
                    },
                );
            }
            Some(agg) => {
                // Add this trait ID to the list
                if !agg.matched_traits.contains(&finding.id) {
                    agg.matched_traits.push(finding.id.clone());
                }

                // Keep the one with higher criticality.
                // Ties: higher confidence, then lexicographically smaller id so
                // parallel trait evaluation order doesn't flip the displayed pick.
                let should_replace = finding.crit > agg.best.crit
                    || (finding.crit == agg.best.crit && finding.conf > agg.best.conf)
                    || (finding.crit == agg.best.crit
                        && finding.conf == agg.best.conf
                        && finding.id < agg.best.id);

                if should_replace {
                    agg.best = finding.clone();
                }
            }
        }
    }

    // Convert aggregated findings to Finding structs with directory as ID
    let mut result: Vec<Finding> = aggregated
        .into_values()
        .map(|agg| {
            let mut result = agg.best;
            result.id = agg.directory;
            result.trait_refs = agg.matched_traits;
            result
        })
        .collect();

    // Add internal findings (not aggregated) to the result
    result.extend(internal_findings);
    result
}

/// Get risk indicator based on criticality
#[allow(dead_code)] // Used by binary target
fn risk_indicator(crit: &Criticality) -> colored::ColoredString {
    use crate::theme;
    match crit {
        Criticality::Filtered => "   ".normal(),
        Criticality::Component => "  ·".dimmed(),
        Criticality::Baseline => theme::paint_baseline("  ·"),
        Criticality::Notable => theme::paint_notable("  •"),
        Criticality::Suspicious => theme::paint_suspicious(" ••"),
        Criticality::Hostile => theme::paint_hostile("•••"),
    }
}

/// Get risk level name
/// Split trait ID into namespace and rest, skipping "cap"/"obj" prefixes
/// e.g., "micro-behaviors/execution/command/subprocess" -> ("exec", "command/subprocess")
/// e.g., "objectives/anti-analysis/debugger/detect" -> ("anti-analysis", "debugger/detect")
/// e.g., "intel/discover/process/getuid" -> ("intel", "discover/process/getuid")
#[allow(dead_code)] // Used by binary target
fn split_trait_id(id: &str) -> (String, String) {
    let parts: Vec<&str> = id.split('/').collect();

    // Skip "cap" or "obj" prefix if present
    let start_idx = if parts.len() > 1 && (parts[0] == "cap" || parts[0] == "obj") {
        1
    } else {
        0
    };

    if parts.len() > start_idx + 1 {
        (
            parts[start_idx].to_string(),
            parts[start_idx + 1..].join("/"),
        )
    } else if parts.len() > start_idx {
        (parts[start_idx].to_string(), parts[start_idx].to_string())
    } else {
        (id.to_string(), id.to_string())
    }
}

/// Namespace categories for grouping findings
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[allow(dead_code)] // Used by binary target
enum Namespace {
    WellKnown,
    Objectives,
    MicroBehaviors,
    Metadata,
    ThirdParty,
}

impl Namespace {
    /// Parse namespace from trait ID prefix
    fn from_trait_id(id: &str) -> Option<Self> {
        let prefix = id.split('/').next()?;
        match prefix {
            "well-known" => Some(Self::WellKnown),
            "objectives" => Some(Self::Objectives),
            "micro-behaviors" => Some(Self::MicroBehaviors),
            "metadata" => Some(Self::Metadata),
            "third_party" | "third-party" => Some(Self::ThirdParty),
            _ => None,
        }
    }

    /// Display name for section header
    fn display_name(&self) -> &'static str {
        match self {
            Self::WellKnown => "WELL-KNOWN",
            Self::Objectives => "OBJECTIVES",
            Self::MicroBehaviors => "MICRO-BEHAVIORS",
            Self::Metadata => "METADATA",
            Self::ThirdParty => "THIRD-PARTY",
        }
    }
}

/// Get sort order for namespace (fixed order: well-known, objectives, micro-behaviors, metadata, third-party)
#[allow(dead_code)] // Used by binary target
fn namespace_sort_order(ns: &str) -> u8 {
    match ns {
        "well-known" => 0,
        "objectives" => 1,
        "micro-behaviors" => 2,
        "metadata" => 3,
        "third-party" | "third_party" => 4,
        _ => 5, // Unknown namespaces go last
    }
}

/// Convert namespace to long name, capitalizing if no explicit mapping exists
#[allow(dead_code)] // Used by binary target
fn namespace_long_name(ns: &str) -> String {
    let mapped = match ns {
        "c2" => Some("COMMAND & CONTROL"),
        "crypto" => Some("CRYPTOGRAPHY"),
        "exfil" => Some("EXFILTRATION"),
        "exec" => Some("EXECUTION"),
        "fs" => Some("FILESYSTEM"),
        "hw" => Some("HARDWARE"),
        "comm" => Some("COMMUNICATION"),
        "os" => Some("OS"),
        "anti-analysis" => Some("ANTI-ANALYSIS"),
        "anti-static" => Some("STATIC EVASION"),
        "anti-forensics" => Some("ANTI-FORENSICS"),
        "privilege-escalation" => Some("PRIVILEGE ESCALATION"),
        "process" => Some("PROCESS"),
        "mem" => Some("MEMORY"),
        "data" => Some("DATA"),
        "impact" => Some("IMPACT"),
        "credential-access" => Some("CREDENTIALS"),
        "lateral" => Some("LATERAL MOVEMENT"),
        "persist" => Some("PERSISTENCE"),
        "discovery" => Some("DISCOVERY"),
        "exploit" => Some("EXPLOIT"),
        "collect" => Some("COLLECTION"),
        "graphics" => Some("GRAPHICS"),
        "interop" => Some("INTEROPERABILITY"),
        "io" => Some("INPUT/OUTPUT"),
        "time" => Some("TIME"),
        "ui" => Some("USER INTERFACE"),
        "meta" => Some("METADATA"),
        _ => None,
    };

    match mapped {
        Some(name) => name.to_string(),
        None => {
            // Full uppercase and replace hyphens with spaces for unknown namespaces
            ns.replace('-', " ").to_uppercase()
        }
    }
}

/// Format evidence string (minimal, deduplicated)
/// Maximum width for evidence display (truncate if longer)
#[allow(dead_code)] // Used by binary target
const EVIDENCE_MAX_WIDTH: usize = 80;

/// Make descriptions more terse by removing redundant explanatory parentheticals
#[allow(dead_code)] // Used by binary target
fn terse_description(desc: &str) -> String {
    // Remove common verbose patterns that are redundant given the context
    desc.replace(" (timing attacks or sandbox detection)", "")
        .replace(" (C2 communication pattern)", "")
        .replace(" (comprehensive stealer)", "")
        .replace(" (monolithic multicall binary)", "")
        .replace(" (packer pattern)", "")
        .replace(" (potential stealer)", "")
        .replace(" (potential keylogger)", "")
        .replace(" (hardcoded alphabet + decode table)", "")
        .replace(" reveals directory contents", "")
        .replace(" (opendir + readdir + stat)", "")
        .replace(".DS_Store ", "")
        .replace(" (excluding known legitimate)", "")
        .trim()
        .to_string()
}

#[allow(dead_code)] // Used by binary target
fn format_evidence(finding: &Finding) -> String {
    // Dedupe values, drop blank/whitespace-only lines from each. If any
    // value spans multiple lines after cleaning, return the full set as a
    // newline-separated block (the renderer indents continuation lines to
    // the evidence column). Otherwise comma-join for compactness.
    let mut seen = std::collections::HashSet::new();
    let values: Vec<String> = finding
        .evidence
        .iter()
        .filter_map(|e| {
            let cleaned: String = e
                .value
                .lines()
                .filter(|l| !l.trim().is_empty())
                .collect::<Vec<_>>()
                .join("\n");
            if cleaned.is_empty() {
                return None;
            }
            if seen.insert(cleaned.clone()) {
                Some(cleaned)
            } else {
                None
            }
        })
        .take(5)
        .collect();

    if values.is_empty() {
        return String::new();
    }

    if values.iter().any(|v| v.contains('\n')) {
        values.join("\n")
    } else {
        values.join(", ")
    }
}

// =============================================================================
// JSONL (Newline-Delimited JSON) Output for Streaming
// =============================================================================

/// JSONL file entry - emitted for each file as it's analyzed
#[allow(dead_code)] // Used by binary target
#[derive(serde::Serialize)]
struct JsonlFileEntry<'a> {
    #[serde(rename = "type")]
    entry_type: &'static str,
    #[serde(flatten)]
    file: &'a crate::types::FileAnalysis,
}

/// JSONL summary entry - emitted at the end of streaming output
#[allow(dead_code)] // Used by binary target
#[derive(serde::Serialize)]
struct JsonlSummary {
    #[serde(rename = "type")]
    entry_type: &'static str,
    files_analyzed: u32,
    #[serde(rename = "x")]
    score: u32,
    hostile: u32,
    suspicious: u32,
    notable: u32,
    duration_ms: u64,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    tools: Vec<String>,
}

/// Minimum confidence required for a finding to contribute to the formula.
/// Higher than the display threshold (0.5) on purpose: the formula is a
/// fingerprint, not an enumeration, so we want only findings the analyzer
/// is confident about.
pub(crate) const FORMULA_MIN_CONF: f32 = 0.65;

/// Canonical filter for formula generation: aggregate by directory, keep
/// notable-or-higher findings with confidence ≥ FORMULA_MIN_CONF.
///
/// Component- and baseline-criticality findings are intentionally dropped:
/// the formula is meant to mirror the CLI's notable-or-higher display, so
/// the JSON `f` field, JSONL `f` field, library `formula_from_report`, and
/// terminal header all share this single source of truth.
pub(crate) fn filter_findings_for_formula(findings: &[Finding]) -> Vec<Finding> {
    let aggregated = aggregate_findings_by_directory(findings);
    aggregated
        .into_iter()
        .filter(|f| f.crit >= Criticality::Notable && f.conf >= FORMULA_MIN_CONF)
        .collect()
}

/// Format a single file analysis as a JSONL line
#[allow(dead_code)] // Used by binary target
pub(crate) fn format_jsonl_line(file: &crate::types::FileAnalysis) -> Result<String> {
    // Compute formula if not already set
    if file.formula.is_none() {
        let mut file_with_formula = file.clone();
        let filtered = filter_findings_for_formula(&file.findings);
        let formula = malecule_bridge::formula_from_findings(&filtered);
        file_with_formula.formula = Some(if formula.is_empty() {
            "∅".to_string()
        } else {
            formula
        });
        let entry = JsonlFileEntry {
            entry_type: "file",
            file: &file_with_formula,
        };
        return Ok(serde_json::to_string(&entry)?);
    }

    let entry = JsonlFileEntry {
        entry_type: "file",
        file,
    };
    Ok(serde_json::to_string(&entry)?)
}

/// Format the summary as a JSONL line (for end of streaming output)
#[allow(dead_code)] // Used by binary target
pub(crate) fn format_jsonl_summary(report: &AnalysisReport) -> Result<String> {
    let summary = report.summary.as_ref();
    let counts = summary.map(|s| &s.counts);

    let entry = JsonlSummary {
        entry_type: "summary",
        files_analyzed: summary
            .map(|s| s.files_analyzed)
            .unwrap_or(report.files.len() as u32),
        score: summary.map(|s| s.score).unwrap_or(0),
        hostile: counts.map(|c| c.hostile).unwrap_or(0),
        suspicious: counts.map(|c| c.suspicious).unwrap_or(0),
        notable: counts.map(|c| c.notable).unwrap_or(0),
        duration_ms: summary
            .map(|s| s.duration_ms)
            .unwrap_or(report.metadata.analysis_duration_ms),
        tools: summary
            .map(|s| s.tools.clone())
            .unwrap_or_else(|| report.metadata.tools_used.clone()),
    };
    Ok(serde_json::to_string(&entry)?)
}

/// Format entire report as JSONL (for non-streaming output)
#[allow(dead_code)] // Used by binary target
pub(crate) fn format_jsonl(report: &AnalysisReport) -> Result<String> {
    let mut lines = Vec::with_capacity(report.files.len() + 1);

    // Emit each file as a line
    for file in &report.files {
        lines.push(format_jsonl_line(file)?);
    }

    // Emit summary at end
    lines.push(format_jsonl_summary(report)?);

    // Join with newlines and add trailing newline for proper JSONL streaming
    Ok(format!("{}\n", lines.join("\n")))
}

/// Format the report as compact, context-centric text for small LLMs.
///
/// Reuses two conventions every model already knows: `grep -n -C2` for content
/// (`N:` = a matched line, `N-` = surrounding context, `--` = a gap) and the
/// compiler diagnostic (`# SEV id desc`) for findings. A location `N` is a
/// 1-based line number for source, or a hex byte offset for binaries and
/// minified one-liners. Findings with no positional anchor render as `.` lines.
///
/// ```text
/// # ctx: N: hit, N- context, -- gap, . no-loc; src text | hex ascii; trailer # H/S/N/B/C/F id desc
/// evil.sh <TAB> sh 4.2KB 142
/// 19- def run():
/// 20: exec(base64.b64decode(p)) # H exec/eval-b64 decode+exec base64
/// .        # N metadata/unsigned unsigned binary
/// ```
/// Options for the context view, shared by cleave's terminal output and
/// litmus's `--format tiny`. Both render the same way; only the knobs differ.
#[derive(Clone, Copy, Debug)]
pub struct TinyOpts {
    /// Max findings shown per file, ranked by `crit × conf` (highest first).
    pub top_n: usize,
    /// Hide findings below this criticality.
    pub min_crit: Criticality,
    /// Lines of context per hit (hit ± `(n-1)/2`). `None` keeps the full
    /// captured window.
    pub context_lines: Option<usize>,
    /// Show only each trait's first (primary) match, not all of them.
    pub first_match_only: bool,
    /// Rich header (`path  type • formula` + rule) vs the minimal
    /// `path\ttype size score` line plus the `# ctx:` legend.
    pub rich_header: bool,
    /// Allow ANSI color (still gated on a tty). The terminal view sets this;
    /// the `tiny` view never colors — it's machine/LLM output.
    pub color: bool,
}

impl TinyOpts {
    /// cleave's default terminal view: top 20, notable+, 3-line windows, one
    /// match per trait.
    #[must_use]
    pub fn terminal() -> Self {
        Self {
            top_n: 20,
            min_crit: Criticality::Notable,
            context_lines: Some(3),
            first_match_only: true,
            rich_header: true,
            color: true,
        }
    }

    /// cleave's `--format tiny` (LLM) view: same selection, minimal header, and
    /// never colored — tiny is machine/LLM output.
    #[must_use]
    pub fn tiny() -> Self {
        Self {
            rich_header: false,
            color: false,
            ..Self::terminal()
        }
    }
}

/// Render the report as a colored, context-centric view per `opts`. Color is
/// auto-disabled when stdout isn't a terminal (so `… | llm` stays plain text);
/// in that plain mode a `---^` arrow marks each match instead of bold/color.
pub fn format_context(report: &AnalysisReport, opts: &TinyOpts) -> String {
    let files: Vec<&FileAnalysis> = report.files.iter().filter(|f| file_has_output(f)).collect();
    if files.is_empty() {
        return String::new();
    }
    let colorize = opts.color && colored::control::SHOULD_COLORIZE.should_colorize();
    let term_width = terminal_width();

    let mut out = String::with_capacity(4096);
    let mut emitted = false;
    for file in files {
        let selected = select_ids(file, opts);
        if selected.is_empty() {
            continue;
        }
        if emitted {
            out.push('\n'); // blank line between file entries
        }
        emitted = true;
        if opts.rich_header {
            rich_header(&mut out, file, term_width);
        } else {
            minimal_header(&mut out, file);
        }
        render_context(&mut out, file, &selected, opts, colorize);
        render_no_anchor(&mut out, file, &selected, opts, colorize);
    }
    // Trailing blank line so consecutive file entries are separated — both
    // archive members (looped above) and separate per-file outputs streamed by
    // a directory scan (each its own `format_context` call).
    if emitted {
        out.push('\n');
    }
    out
}

/// The LLM `--format tiny` view.
#[must_use]
pub fn format_tiny(report: &AnalysisReport) -> String {
    format_context(report, &TinyOpts::tiny())
}

/// Whether a file contributes anything to the context view.
fn file_has_output(file: &FileAnalysis) -> bool {
    file.findings.iter().any(|f| tiny_should_show(f, file))
}

/// The top-`n` finding ids to show, ranked by `crit × conf` (highest first) and
/// floored at `min_crit` (after the usual component/filtered gating).
fn select_ids<'a>(file: &'a FileAnalysis, opts: &TinyOpts) -> Vec<&'a str> {
    let mut scored: HashMap<&str, f32> = HashMap::new();
    for f in &file.findings {
        if f.crit < opts.min_crit || !tiny_should_show(f, file) {
            continue;
        }
        let score = f.conf * f32::from(f.crit as u8);
        scored
            .entry(f.id.as_str())
            .and_modify(|s| *s = s.max(score))
            .or_insert(score);
    }
    let mut ranked: Vec<(&str, f32)> = scored.into_iter().collect();
    ranked.sort_unstable_by(|a, b| b.1.total_cmp(&a.1).then_with(|| a.0.cmp(b.0)));
    ranked.truncate(opts.top_n);
    ranked.into_iter().map(|(id, _)| id).collect()
}

/// Minimal `path\ttype size score` header for the tiny/LLM view.
fn minimal_header(out: &mut String, file: &FileAnalysis) {
    out.push_str(&tiny_field(&file.path));
    out.push('\t');
    out.push_str(&tiny_field(&file.file_type));
    out.push(' ');
    out.push_str(&format_size(file.size));
    out.push(' ');
    out.push_str(&file.score.to_string());
    out.push('\n');
}

/// Emit the merged context: `grep -n -C2`-style lines with `# SEV id desc`
/// trailers, `--` between non-contiguous windows.
fn render_context(
    out: &mut String,
    file: &FileAnalysis,
    selected: &[&str],
    opts: &TinyOpts,
    colorize: bool,
) {
    let radius = opts.context_lines.map_or(2u64, |n| (n.saturating_sub(1) / 2) as u64);
    let hex_file = file.context.first().is_some_and(|l| l.hex);
    let unit = if hex_file { crate::context::HEX_STRIDE } else { 1 };
    let span = radius.saturating_mul(unit);

    // Each selected trait's match locations, in file order.
    let mut locs_by_id: HashMap<&str, Vec<u64>> = HashMap::new();
    for line in &file.context {
        for n in &line.notes {
            if selected.contains(&n.id.as_str()) {
                let locs = locs_by_id.entry(n.id.as_str()).or_default();
                if locs.last() != Some(&line.loc) {
                    locs.push(line.loc);
                }
            }
        }
    }

    // Pick where each trait is shown. In rank order (highest crit×conf first),
    // a trait takes its first match whose ±window doesn't overlap a window a
    // higher-ranked trait already claimed; failing that, its first match.
    let mut shown_at: HashMap<u64, Vec<&str>> = HashMap::new();
    let mut claimed: Vec<(u64, u64)> = Vec::new();
    for &id in selected {
        let Some(locs) = locs_by_id.get(id) else {
            continue;
        };
        let picks: Vec<u64> = if opts.first_match_only {
            let pick = locs
                .iter()
                .copied()
                .find(|&loc| {
                    let (lo, hi) = (loc.saturating_sub(span), loc.saturating_add(span));
                    !claimed.iter().any(|&(c0, c1)| lo <= c1 && c0 <= hi)
                })
                .or_else(|| locs.first().copied());
            pick.into_iter().collect()
        } else {
            locs.clone()
        };
        for loc in picks {
            shown_at.entry(loc).or_default().push(id);
            claimed.push((loc.saturating_sub(span), loc.saturating_add(span)));
        }
    }
    if shown_at.is_empty() {
        return;
    }
    let hits: Vec<u64> = shown_at.keys().copied().collect();
    let marker = comment_marker(&file.file_type);
    // A row is shown when it falls inside some featured trait's window.
    let in_window = |loc: u64| hits.iter().any(|&h| loc.abs_diff(h) <= span);
    // Highlight (and below, annotate) *every* match that lands in a shown window,
    // not only the featured traits. A lesser match sharing the window — a
    // component or baseline trait just ahead of or behind the feature — is
    // flagged at its own level instead of rendering as blank context.
    let mut spans: Vec<(u64, u64, Criticality)> = Vec::new();
    for l in &file.context {
        if in_window(l.loc) {
            for n in &l.notes {
                spans.push((n.off, n.off + u64::from(n.len.max(1)), n.crit));
            }
        }
    }
    let loc_width = file
        .context
        .iter()
        .map(|l| {
            if l.hex {
                format!("{:x}", l.loc).len()
            } else {
                l.loc.to_string().len()
            }
        })
        .max()
        .unwrap_or(1);

    let mut prev: Option<u64> = None;
    let mut prev_rendered = false;
    // A row's second-strongest trait "flows" onto the next row, but only if that
    // row has no comment of its own; otherwise it's dropped (it's lower-rank than
    // what the next row already shows).
    let mut pending: Option<&Note> = None;
    for line in &file.context {
        // A hex continuation row (unmatched, ends in `…`) only appears when it
        // actually trails a rendered run — never on its own, so it can't lead a
        // window as an orphan.
        let is_cont = line.hex && line.notes.is_empty();
        let show = if is_cont {
            prev_rendered
        } else {
            in_window(line.loc)
        };
        if !show {
            prev_rendered = false;
            pending = None; // don't carry a flowed comment across a hidden gap
            continue; // outside every shown window
        }
        // Show every match on this row, so context bytes carrying a lesser trait
        // are highlighted rather than left blank.
        let notes: Vec<&Note> = line.notes.iter().collect();
        let mut ranked = notes.clone();
        ranked.sort_by(|a, b| b.crit.cmp(&a.crit).then_with(|| a.off.cmp(&b.off)));
        let own_top = ranked.first().copied();
        // This row's comment: its own strongest trait, else a comment flowed from
        // the previous row (`↖`). The next-strongest own trait flows onward.
        let comment = match own_top {
            Some(top) => Some((top, false)),
            None => pending.map(|n| (n, true)),
        };
        pending = if own_top.is_some() {
            ranked.get(1).copied()
        } else {
            None
        };

        // Source uses `⋯`/`--` between non-adjacent windows; hex marks the break
        // with the trailing `…` continuation row instead.
        if !hex_file && prev.is_some_and(|p| line.loc > p.saturating_add(unit)) {
            if colorize {
                // Indent the gap glyph under the content column (gutter 3 + space
                // + loc + 2 spaces) so it falls beneath the code.
                out.push_str(&" ".repeat(loc_width + 6));
                out.push_str(&"⋯".bright_black().to_string());
                out.push('\n');
            } else {
                out.push_str("--\n");
            }
        }
        prev = Some(line.loc);
        prev_rendered = true;
        render_line(out, line, &notes, comment, marker, loc_width, &spans, colorize);
    }
}

/// Line-comment marker for the sample's language; `//` for binary and anything
/// C-family, so the annotation reads like a comment the analyst wrote.
fn comment_marker(file_type: &str) -> &'static str {
    match file_type {
        "python" | "shell" | "bash" | "ruby" | "perl" | "r" | "powershell" | "yaml" | "toml"
        | "makefile" | "dockerfile" | "systemd" | "desktop" | "text" | "ini" | "properties" => "#",
        "lua" | "sql" | "haskell" | "applescript" | "vbs" | "vba" => "--",
        _ => "//",
    }
}


/// Column the trailing comment soft-aligns to (from the start of the content).
const COMMENT_COL: usize = 46;

/// Text width of a full hex row (`hex_ascii` output for `HEX_STRIDE` bytes):
/// `n` pairs of `"XX "` + a separator space + `n` ascii chars. Hex comments pad
/// to this column so they all align like a hex editor's annotation gutter.
fn hex_comment_col() -> usize {
    let n = crate::context::HEX_STRIDE as usize;
    n * 3 + 1 + n
}

/// Render one context line. Colored: a `●` severity gutter, right-aligned line
/// number, the code with its match highlighted, and the line's top trait as a
/// comment in the sample's language. Plain: grep-style with a `---^` arrow.
fn render_line(
    out: &mut String,
    line: &ContextLine,
    notes: &[&Note],
    comment: Option<(&Note, bool)>, // (trait, is_flow) — is_flow → `↖` pointing at the row above
    marker: &str,
    loc_width: usize,
    spans: &[(u64, u64, Criticality)],
    colorize: bool,
) {
    let base = line.addr.unwrap_or(line.loc);
    // Gutter dots reflect the row's own strongest match (a flowed comment points
    // at a match on a different row, so it doesn't drive this row's gutter).
    let gutter_top = notes
        .iter()
        .copied()
        .max_by_key(|n| (n.crit, std::cmp::Reverse(n.off)));
    let loc_str = if line.hex {
        format!("{:x}", line.loc)
    } else {
        line.loc.to_string()
    };

    if colorize {
        // 1–3 dots by severity (`•••`/` ••`/`  •`) so the level reads even on a
        // monochrome display, where color alone wouldn't.
        let gutter = gutter_top.map_or_else(
            || "   ".to_string(),
            |n| risk_indicator(&n.crit).to_string(),
        );
        out.push_str(&gutter);
        out.push(' ');
        out.push_str(&format!("{loc_str:>loc_width$}").bright_black().to_string());
        out.push_str("  ");
        if line.hex {
            if notes.is_empty() {
                // Continuation / pure-context hex row: nothing of its own to
                // highlight, and its `…` tokens aren't parseable as hex pairs.
                out.push_str(&line.text.bright_black().to_string());
            } else {
                out.push_str(&paint_hex(&line.text, line.loc, spans));
            }
        } else {
            out.push_str(&paint_content(&line.text, base, notes));
        }
        if let Some((n, is_flow)) = comment {
            // Hex comments align to a fixed column (a full row's width) so every
            // annotation lines up like a hex editor; source soft-aligns.
            let target = if line.hex { hex_comment_col() } else { COMMENT_COL };
            let pad = target.saturating_sub(line.text.chars().count()).max(2);
            let (r, g, b) = crit_rgb(n.crit);
            let lead = if is_flow {
                format!("{marker} ↖")
            } else {
                marker.to_string()
            };
            out.push_str(&" ".repeat(pad));
            out.push_str(&lead.truecolor(r, g, b).to_string()); // marker tinted by severity
            out.push(' ');
            out.push_str(&terse_description(&n.desc).bright_white().to_string());
        }
        out.push('\n');
        return;
    }

    // Plain (piped / LLM): grep-style, language comment with the severity letter,
    // and a `---^` arrow under the match.
    out.push_str(&loc_str);
    out.push(if notes.is_empty() { '-' } else { ':' });
    out.push(' ');
    out.push_str(&line.text);
    if let Some((n, is_flow)) = comment {
        let arrow = if is_flow { "↖ " } else { "" };
        out.push_str(&format!(
            " {marker} {arrow}{} {}",
            n.crit.letter(),
            terse_description(&n.desc)
        ));
    }
    out.push('\n');
    if !line.hex && !notes.is_empty() {
        let prefix = loc_str.chars().count() + 2; // loc + sep + space
        if let Some(arrow) = arrow_line(&line.text, base, notes, prefix) {
            out.push_str(&arrow);
            out.push('\n');
        }
    }
}

/// The theme's truecolor for a criticality — the brand severity palette (coral /
/// gold / azure / forest / gray). The line body is painted in this hue regular,
/// the matched evidence the same hue bold.
fn crit_rgb(crit: Criticality) -> (u8, u8, u8) {
    match crit {
        Criticality::Hostile => crate::theme::HOSTILE_RGB,
        Criticality::Suspicious => crate::theme::SUSPICIOUS_RGB,
        Criticality::Notable => crate::theme::NOTABLE_RGB,
        Criticality::Baseline => crate::theme::BASELINE_RGB,
        _ => crate::theme::COMPONENT_RGB,
    }
}

/// Paint `text` with the theme severity painter (hostile/suspicious bold).
fn paint_by_crit(crit: Criticality, text: &str) -> colored::ColoredString {
    match crit {
        Criticality::Hostile => crate::theme::paint_hostile(text),
        Criticality::Suspicious => crate::theme::paint_suspicious(text),
        Criticality::Notable => crate::theme::paint_notable(text),
        Criticality::Baseline => crate::theme::paint_baseline(text),
        _ => crate::theme::paint_component(text),
    }
}

/// Color a source content line: a context-only line is dim grey; on a hit line
/// only the matched evidence is highlighted (severity hue, bold) and the rest of
/// the code stays the terminal's default color, so it reads naturally.
fn paint_content(text: &str, base: u64, notes: &[&Note]) -> String {
    if notes.is_empty() {
        return text.bright_black().to_string(); // context line: quiet gray
    }
    let mut spans: Vec<(usize, usize, Criticality)> = notes
        .iter()
        .filter_map(|n| {
            let start = usize::try_from(n.off.checked_sub(base)?).ok()?;
            let end = start.checked_add(n.len as usize)?;
            text.get(start..end).map(|_| (start, end, n.crit))
        })
        .collect();
    spans.sort_unstable_by_key(|&(s, _, _)| s);

    let mut buf = String::new();
    let mut pos = 0;
    for (start, end, crit) in spans {
        if start < pos {
            continue;
        }
        if let Some(pre) = text.get(pos..start) {
            buf.push_str(pre); // default color
        }
        if let Some(ev) = text.get(start..end) {
            let (er, eg, eb) = crit_rgb(crit);
            buf.push_str(&ev.truecolor(er, eg, eb).bold().to_string());
        }
        pos = end;
    }
    buf.push_str(text.get(pos..).unwrap_or(""));
    buf
}

/// Color a hex|ascii row: dim grey, with the matched bytes (both the hex pairs
/// and their ascii) highlighted in the severity hue. `spans` are absolute byte
/// ranges, so a match that wraps across rows lights up its slice in each row.
/// Layout (from `hex_ascii`): `N` bytes as `"XX "` (3 chars each), a space, then
/// `N` ascii chars — so byte `i`'s hex is at `3i..3i+2` and its ascii at `3N+1+i`.
fn paint_hex(text: &str, row_base: u64, spans: &[(u64, u64, Criticality)]) -> String {
    let chars: Vec<char> = text.chars().collect();
    let n = chars.len().saturating_sub(1) / 4; // bytes in this row
    let mut style: Vec<Option<Criticality>> = vec![None; chars.len()];
    for i in 0..n {
        let off = row_base + i as u64;
        if let Some(&(_, _, crit)) = spans.iter().find(|&&(lo, hi, _)| lo <= off && off < hi) {
            for pos in [3 * i, 3 * i + 1, 3 * n + 1 + i] {
                if let Some(slot) = style.get_mut(pos) {
                    *slot = Some(crit);
                }
            }
        }
    }
    let mut buf = String::new();
    let mut i = 0;
    while i < chars.len() {
        let cur = style[i];
        let mut j = i;
        while j < chars.len() && style[j] == cur {
            j += 1;
        }
        let seg: String = chars[i..j].iter().collect();
        match cur {
            Some(crit) => {
                let (r, g, b) = crit_rgb(crit);
                buf.push_str(&seg.truecolor(r, g, b).bold().to_string());
            }
            None => buf.push_str(&seg.bright_black().to_string()),
        }
        i = j;
    }
    buf
}

/// Emit selected findings that have *no anchorable location at all* (metric /
/// size / structural facts) as `.` lines. Findings that have an offset but lost
/// the overlap dedup are not re-listed here — they're subsumed by their winner.
fn render_no_anchor(
    out: &mut String,
    file: &FileAnalysis,
    selected: &[&str],
    opts: &TinyOpts,
    colorize: bool,
) {
    let anchored: HashSet<&str> = file
        .context
        .iter()
        .flat_map(|l| l.notes.iter().map(|n| n.id.as_str()))
        .collect();
    let sel: HashSet<&str> = selected.iter().copied().collect();

    let mut rest: Vec<&Finding> = file
        .findings
        .iter()
        .filter(|f| {
            f.crit >= opts.min_crit
                && sel.contains(f.id.as_str())
                && !anchored.contains(f.id.as_str())
                // (a) drop overlap-dedup losers: they *have* an offset but were
                // collapsed into a higher trait's window. Only genuinely
                // location-less findings remain.
                && !f.evidence.iter().any(|e| e.byte_offset().is_some())
        })
        .collect();
    rest.sort_unstable_by(|a, b| b.crit.cmp(&a.crit).then_with(|| a.id.cmp(&b.id)));

    let mut seen = HashSet::new();
    for f in rest {
        if !seen.insert(f.id.as_str()) {
            continue;
        }
        let desc = terse_description(&f.desc);
        if colorize {
            // Dots gutter for severity, then the description in bright white —
            // consistent with anchored lines, just with no location.
            out.push_str(&format!(
                "{}  {} {}\n",
                risk_indicator(&f.crit),
                "#".bright_black(),
                desc.bright_white()
            ));
        } else {
            out.push_str(&format!(". # {} {desc}\n", f.crit.letter()));
        }
    }
}

fn tiny_field(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// cleave's default terminal view: colored, top-20, notable+, 3-line windows.
pub(crate) fn format_terminal_ctx(report: &AnalysisReport) -> String {
    format_context(report, &TinyOpts::terminal())
}

/// Rich file header: `path  type • formula` then a full-width rule.
fn rich_header(out: &mut String, file: &FileAnalysis, term_width: usize) {
    let formula_findings = filter_findings_for_formula(&file.findings);
    let formula = malecule_bridge::formula_from_findings(&formula_findings);
    let file_type_display = display_file_type(&file.file_type);
    let type_formula = if formula.is_empty() {
        file_type_display
    } else {
        format!("{file_type_display} • {formula}")
    };
    let display_path = if file.depth > 0 {
        file.path
            .rsplit(crate::types::file_analysis::ARCHIVE_DELIMITER)
            .next()
            .or_else(|| {
                file.path
                    .rsplit(crate::types::file_analysis::ENCODING_DELIMITER)
                    .next()
            })
            .unwrap_or(&file.path)
    } else {
        &file.path
    };
    let counts = severity_legend(file);
    out.push_str(&format!(
        "{}  {}{}\n",
        display_path.bright_white().bold(),
        type_formula.bright_black(),
        counts,
    ));
    out.push_str(&format!("{}\n", file_rule(term_width)));
}

/// A compact, colored severity tally for the header: `  3H 2S 4N`, counting each
/// distinct shown finding once. Empty tiers are omitted.
fn severity_legend(file: &FileAnalysis) -> String {
    let (mut hostile, mut susp, mut notable) = (0u32, 0u32, 0u32);
    let mut seen = HashSet::new();
    for f in &file.findings {
        if !tiny_should_show(f, file) || !seen.insert(f.id.as_str()) {
            continue;
        }
        match f.crit {
            Criticality::Hostile => hostile += 1,
            Criticality::Suspicious => susp += 1,
            Criticality::Notable => notable += 1,
            _ => {}
        }
    }
    let mut parts: Vec<String> = Vec::new();
    if hostile > 0 {
        parts.push(paint_by_crit(Criticality::Hostile, &format!("{hostile}H")).to_string());
    }
    if susp > 0 {
        parts.push(paint_by_crit(Criticality::Suspicious, &format!("{susp}S")).to_string());
    }
    if notable > 0 {
        parts.push(paint_by_crit(Criticality::Notable, &format!("{notable}N")).to_string());
    }
    if parts.is_empty() {
        String::new()
    } else {
        format!("   {}", parts.join(" "))
    }
}

/// Build a `---^` pointer line: a caret under where each note's match starts in
/// `text` (a short `---` shaft leading into it), offset by the line's `prefix`
/// width. Returns `None` when no match maps into the rendered text.
fn arrow_line(text: &str, base: u64, notes: &[&Note], prefix: usize) -> Option<String> {
    let mut cols: Vec<usize> = notes
        .iter()
        .filter_map(|n| {
            let byte_col = usize::try_from(n.off.checked_sub(base)?).ok()?;
            // Char column so the caret aligns under multi-byte text.
            text.get(..byte_col)
                .map(|pre| prefix + pre.chars().count())
        })
        .collect();
    if cols.is_empty() {
        return None;
    }
    cols.sort_unstable();
    cols.dedup();

    let mut buf = vec![' '; cols.last().copied().unwrap_or(0) + 1];
    for c in cols {
        buf[c] = '^';
        // Draw up to three `-` of shaft to the left, stopping at any marker.
        for d in 1..=3 {
            match c.checked_sub(d) {
                Some(i) if buf[i] == ' ' => buf[i] = '-',
                _ => break,
            }
        }
    }
    Some(buf.into_iter().collect())
}

fn tiny_should_show(finding: &Finding, file: &FileAnalysis) -> bool {
    if finding.crit != Criticality::Component {
        return true;
    }

    file.findings
        .iter()
        .any(|f| f.trait_refs.iter().any(|id| id == &finding.id))
}

/// Format byte size as human-readable string (compact)
fn format_size(bytes: u64) -> String {
    if bytes == 0 {
        return String::new();
    }
    const KB: u64 = 1024;
    const MB: u64 = 1024 * KB;
    const GB: u64 = 1024 * MB;
    if bytes >= GB {
        format!("{:.1}GB", bytes as f64 / GB as f64)
    } else if bytes >= MB {
        format!("{:.1}MB", bytes as f64 / MB as f64)
    } else if bytes >= KB {
        format!("{}KB", bytes / KB)
    } else {
        format!("{}B", bytes)
    }
}

/// Parse JSONL (newline-delimited JSON) back to AnalysisReport
#[allow(dead_code)] // Used by binary target
pub(crate) fn parse_jsonl(jsonl: &str) -> Result<AnalysisReport> {
    let mut files = Vec::new();
    let mut summary = None;
    let mut version = "3".to_string();

    // Parse each line as a JSON entry
    for line in jsonl.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }

        let value: serde_json::Value = serde_json::from_str(trimmed)?;
        let entry_type = value.get("type").and_then(|v| v.as_str());

        match entry_type {
            Some("file") => {
                let file: crate::types::FileAnalysis = serde_json::from_value(value)?;
                files.push(file);
            }
            Some("summary") => {
                if let Some(v) = value
                    .get("version")
                    .or_else(|| value.get("schema_version"))
                    .and_then(|v| v.as_str())
                {
                    version = v.to_string();
                }
                let tools: Vec<String> = value
                    .get("tools")
                    .or_else(|| value.get("tools_used"))
                    .and_then(|v| v.as_array())
                    .map(|arr| {
                        arr.iter()
                            .filter_map(|v| v.as_str().map(str::to_string))
                            .collect()
                    })
                    .unwrap_or_default();
                let errors: Vec<String> = value
                    .get("errors")
                    .and_then(|v| v.as_array())
                    .map(|arr| {
                        arr.iter()
                            .filter_map(|v| v.as_str().map(str::to_string))
                            .collect()
                    })
                    .unwrap_or_default();
                let duration_ms = value
                    .get("duration_ms")
                    .or_else(|| value.get("analysis_duration_ms"))
                    .and_then(serde_json::Value::as_u64)
                    .unwrap_or(0);

                summary = Some(crate::types::ReportSummary {
                    files_analyzed: value
                        .get("files_analyzed")
                        .and_then(serde_json::Value::as_u64)
                        .unwrap_or(files.len() as u64) as u32,
                    counts: crate::types::FindingCounts {
                        hostile: value
                            .get("hostile")
                            .and_then(serde_json::Value::as_u64)
                            .unwrap_or(0) as u32,
                        suspicious: value
                            .get("suspicious")
                            .and_then(serde_json::Value::as_u64)
                            .unwrap_or(0) as u32,
                        notable: value
                            .get("notable")
                            .and_then(serde_json::Value::as_u64)
                            .unwrap_or(0) as u32,
                    },
                    score: 0,
                    duration_ms,
                    tools,
                    errors,
                });
            }
            _ => {
                // Unknown entry type, skip
            }
        }
    }

    // Create a minimal AnalysisReport with the parsed data
    let target = if let Some(first_file) = files.first() {
        crate::types::TargetInfo {
            path: first_file.path.clone(),
            file_type: first_file.file_type.clone(),
            sha256: first_file.sha256.clone(),
            size_bytes: first_file.size,
            architectures: None,
        }
    } else {
        crate::types::TargetInfo {
            path: "unknown".to_string(),
            file_type: "unknown".to_string(),
            sha256: String::new(),
            size_bytes: 0,
            architectures: None,
        }
    };

    let mut report = AnalysisReport::new(target);
    report.version = version;
    report.files = files;
    report.summary = summary;

    Ok(report)
}

/// Get terminal width, defaulting to 100 if unavailable
#[allow(dead_code)] // Used by binary target
fn terminal_width() -> usize {
    terminal_size::terminal_size()
        .map(|(w, _)| w.0 as usize)
        .unwrap_or(100)
}

/// Truncate string to max width, using ellipsis (…) if needed
#[allow(dead_code)] // Used by binary target
fn truncate_with_ellipsis(s: &str, max_width: usize) -> String {
    if s.len() <= max_width {
        return s.to_string();
    }
    if max_width <= 1 {
        return "…".to_string();
    }
    // Find char boundary for truncation
    let mut end = max_width - 1;
    while !s.is_char_boundary(end) && end > 0 {
        end -= 1;
    }
    format!("{}…", &s[..end])
}

fn display_file_type(file_type: &str) -> String {
    file_type.to_uppercase()
}

/// Render a section label as a muted 256-color pill — bold white on dark bg.
/// Hue encodes the namespace: red=well-known, magenta=objectives, blue=behaviors, gray=metadata.
#[allow(dead_code)] // Used by binary target
fn section_pill(ns: &Namespace) -> colored::ColoredString {
    let (name, r, g, b) = match ns {
        Namespace::WellKnown => (ns.display_name(), 95, 0, 0), // dark red (256 idx 52)
        Namespace::Objectives => (ns.display_name(), 95, 0, 95), // dark magenta (53)
        Namespace::MicroBehaviors => (ns.display_name(), 0, 0, 95), // dark blue (17)
        Namespace::Metadata => (ns.display_name(), 48, 48, 48), // dark gray (236)
        Namespace::ThirdParty => (ns.display_name(), 120, 56, 0), // dark orange
    };
    format!(" {name} ").bold().white().on_truecolor(r, g, b)
}

/// Full-width slate-blue rule used as a file-boundary marker. Routed
/// through `theme::paint_rule` and `theme::RULE_CHAR` so analyze and
/// diff share the exact same separator.
#[allow(dead_code)] // Used by binary target
fn file_rule(width: usize) -> colored::ColoredString {
    let rule: String = crate::theme::RULE_CHAR.to_string().repeat(width);
    crate::theme::paint_rule(rule)
}

/// Bullet indicator based on criticality: • notable, •• suspicious, ••• hostile
#[allow(dead_code)] // Used by binary target
fn bullet_for_crit(crit: &Criticality) -> colored::ColoredString {
    use crate::theme;
    match crit {
        Criticality::Hostile => theme::paint_hostile("•••"),
        Criticality::Suspicious => theme::paint_suspicious(" ••"),
        _ => theme::paint_baseline("  •"),
    }
}

/// Colorize text based on criticality.
#[allow(dead_code)] // Used by binary target
fn colorize_by_crit(text: &str, crit: &Criticality) -> colored::ColoredString {
    use crate::theme;
    match crit {
        Criticality::Hostile => theme::paint_hostile(text),
        Criticality::Suspicious => theme::paint_suspicious(text),
        _ => theme::paint_baseline(text),
    }
}

/// Extract short trait ID (strip namespace prefix)
/// e.g., "well-known/malware/BPFDoor" -> "BPFDoor"
/// e.g., "objectives/c2/http/beacon" -> "c2/http/beacon"
/// e.g., "micro-behaviors/fs/read/file" -> "fs/read/file"
#[allow(dead_code)] // Used by binary target
fn short_trait_id(id: &str) -> String {
    let parts: Vec<&str> = id.split('/').collect();
    if parts.len() > 1 {
        // Skip namespace prefix (well-known, objectives, micro-behaviors)
        let first = parts[0];
        if first == "well-known"
            || first == "objectives"
            || first == "micro-behaviors"
            || first == "metadata"
            || first == "third_party"
            || first == "third-party"
        {
            return parts[1..].join("/");
        }
    }
    id.to_string()
}

/// Format analysis report for terminal display
/// Uses the v2 flat files array structure.
#[allow(dead_code)] // Used by binary target
pub(crate) fn format_terminal(report: &AnalysisReport) -> String {
    let mut output = String::new();
    let term_width = terminal_width();

    // Iterate over files that have findings
    for file in &report.files {
        // Skip files with no findings
        if file.findings.is_empty() {
            continue;
        }

        // Per RULES.md: components are hidden from terminal output unless a
        // matched composite that references them fires. Build the set of
        // component IDs referenced by notable-or-higher composites, then keep
        // components only when they appear in that set.
        let referenced_component_ids: HashSet<&str> = file
            .findings
            .iter()
            .filter(|f| f.crit >= Criticality::Notable && f.conf >= 0.5)
            .flat_map(|f| f.trait_refs.iter().map(String::as_str))
            .collect();

        let pre_filtered: Vec<Finding> = file
            .findings
            .iter()
            .filter(|f| f.conf >= 0.5)
            .filter(|f| {
                f.crit >= Criticality::Notable
                    || (f.crit == Criticality::Component
                        && referenced_component_ids.contains(f.id.as_str()))
            })
            .cloned()
            .collect();

        // Aggregate remaining findings by directory path
        let filtered = aggregate_findings_by_directory(&pre_filtered);

        if filtered.is_empty() {
            continue;
        }

        // Group findings by namespace
        let mut by_namespace: HashMap<Namespace, Vec<&Finding>> = HashMap::new();
        for finding in &filtered {
            if let Some(ns) = Namespace::from_trait_id(&finding.id) {
                by_namespace.entry(ns).or_default().push(finding);
            }
        }

        // Sort findings within each namespace by criticality (hostile first)
        for findings in by_namespace.values_mut() {
            findings.sort_unstable_by(|a, b| b.crit.cmp(&a.crit).then_with(|| a.id.cmp(&b.id)));
        }

        // Pre-calculate column widths across ALL findings in this file
        let all_findings: Vec<&&Finding> = by_namespace.values().flat_map(|v| v.iter()).collect();

        let trait_width = all_findings
            .iter()
            .map(|f| short_trait_id(&f.id).len())
            .max()
            .unwrap_or(20);

        let natural_desc_width = all_findings
            .iter()
            .map(|f| terse_description(&f.desc).len())
            .max()
            .unwrap_or(30);

        // Reserve at least MIN_EVIDENCE_WIDTH columns for evidence by capping the
        // description column. One overly long description would otherwise push
        // evidence off the screen, leaving every row with just a stray `…`.
        // Layout overhead: bullet(3) + space(1) + trait + 2 spaces + 2 spaces = 8 + trait_width
        // 24 cols accommodates two short kv-array members like
        // `[lzma_crc32, lzma_crc64]` — descriptions truncate hard
        // first since they're often paraphrasable from the trait id.
        const MIN_EVIDENCE_WIDTH: usize = 24;
        let overhead = 8 + trait_width;
        let max_desc_width = term_width.saturating_sub(overhead + MIN_EVIDENCE_WIDTH);
        let desc_width = natural_desc_width.min(max_desc_width);

        let evidence_width = term_width.saturating_sub(overhead + desc_width);

        // Generate formula from the canonical formula filter (not the
        // display-aggregated `filtered` set above, which includes referenced
        // components). Keeps the header formula identical to the JSON `f`.
        let formula_findings = filter_findings_for_formula(&file.findings);
        let formula = malecule_bridge::formula_from_findings(&formula_findings);

        let file_type_display = display_file_type(&file.file_type);

        // File header: [indent] path  type • formula
        let type_formula = if formula.is_empty() {
            file_type_display
        } else {
            format!("{} • {}", file_type_display, formula)
        };

        // Indent nested files (archive members, embedded binaries, decoded payloads)
        let indent = "  ".repeat(file.depth as usize);
        // Strip virtual path prefixes (!!member, ##encoding) for display if depth > 0
        let display_path = if file.depth > 0 {
            file.path
                .rsplit(crate::types::file_analysis::ARCHIVE_DELIMITER)
                .next()
                .or_else(|| {
                    file.path
                        .rsplit(crate::types::file_analysis::ENCODING_DELIMITER)
                        .next()
                })
                .unwrap_or(&file.path)
        } else {
            &file.path
        };

        output.push_str(&format!(
            "{}{}  {}\n",
            indent,
            display_path.bright_white().bold(),
            type_formula.bright_black()
        ));
        let rule_width = term_width.saturating_sub(indent.len());
        output.push_str(&format!("{}{}\n", indent, file_rule(rule_width)));

        // Render namespaces in fixed order: WELL-KNOWN, OBJECTIVES, MICRO-BEHAVIORS, METADATA, THIRD-PARTY.
        // First section follows the file rule with no gap; later sections get a leading blank.
        let mut first_section = true;
        for ns in [
            Namespace::WellKnown,
            Namespace::Objectives,
            Namespace::MicroBehaviors,
            Namespace::Metadata,
            Namespace::ThirdParty,
        ] {
            let Some(findings) = by_namespace.get(&ns) else {
                continue; // Skip empty sections
            };

            if !first_section {
                output.push('\n');
            }
            first_section = false;

            output.push_str(&format!("{}\n", section_pill(&ns)));

            // Bullet (3) + space (1) + trait + 2 spaces + desc + 2 spaces.
            // Continuation lines for multi-line evidence start at this column.
            let evidence_col = 3 + 1 + trait_width + 2 + desc_width + 2;
            let evidence_indent = " ".repeat(evidence_col);
            // Cap multi-line evidence so a single huge match doesn't drown
            // the rest of the output. Beyond the cap, the last visible line
            // gets a trailing ellipsis.
            const MAX_EVIDENCE_LINES: usize = 4;

            // Render each finding
            for finding in findings {
                let trait_id = short_trait_id(&finding.id);
                let desc = terse_description(&finding.desc);
                let evidence = format_evidence(finding);

                // Build the line with proper column alignment
                // Format: ● trait_id  description  evidence
                let bullet = bullet_for_crit(&finding.crit);
                let padded_trait = format!("{:width$}", trait_id, width = trait_width);
                let truncated_desc = truncate_with_ellipsis(&desc, desc_width);
                let padded_desc = format!("{:width$}", truncated_desc, width = desc_width);

                let raw_lines: Vec<&str> = evidence.lines().collect();
                let (visible_lines, overflow) = if raw_lines.len() > MAX_EVIDENCE_LINES {
                    (&raw_lines[..MAX_EVIDENCE_LINES], true)
                } else {
                    (&raw_lines[..], false)
                };

                if visible_lines.is_empty() {
                    output.push_str(&format!(
                        "{} {}  {}\n",
                        bullet,
                        padded_trait,
                        colorize_by_crit("", &finding.crit)
                    ));
                    continue;
                }

                for (i, line) in visible_lines.iter().enumerate() {
                    let truncated = truncate_with_ellipsis(line, evidence_width);
                    let colored = colorize_by_crit(&truncated, &finding.crit);

                    if i == 0 {
                        output.push_str(&format!(
                            "{} {}  {}  {}\n",
                            bullet, padded_trait, padded_desc, colored
                        ));
                    } else {
                        output.push_str(&format!("{}{}\n", evidence_indent, colored));
                    }
                }
                // Overflow indicator on its own line: dimmed `…` at the
                // evidence column. Unambiguous "more lines below were
                // dropped" without doubling up with per-line truncation
                // ellipses.
                if overflow {
                    output.push_str(&format!(
                        "{}{}\n",
                        evidence_indent,
                        colorize_by_crit("…", &finding.crit)
                    ));
                }
            }
        }

        // Trailing blank after all sections separates this file from the next.
        output.push('\n');
    }

    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{AnalysisReport, Evidence, FindingKind, TargetInfo, YaraMatch};
    use chrono::Utc;

    fn create_test_report(findings: Vec<Finding>, yara_matches: Vec<YaraMatch>) -> AnalysisReport {
        let mut report = AnalysisReport {
            version: "3.0".to_string(),
            analysis_timestamp: Some(Utc::now()),
            target: TargetInfo {
                path: "/test/sample.bin".to_string(),
                file_type: "ELF".to_string(),
                size_bytes: 12345,
                sha256: "def456abc".to_string(),
                architectures: Some(vec!["x86_64".to_string()]),
            },
            findings,
            context: vec![],
            traits: vec![],
            structure: vec![],
            functions: vec![],
            strings: vec![],
            sections: vec![],
            imports: vec![],
            exports: vec![],
            yara_matches,
            syscalls: vec![],
            filefacts: None,
            values_tree: None,
            filefacts_metrics: None,
            paths: vec![],
            directories: vec![],
            comments: vec![],
            env_vars: vec![],
            archive_contents: vec![],
            scanned_path: None,
            files: vec![],
            summary: None,
            metadata: crate::types::AnalysisMetadata {
                analysis_duration_ms: 100,
                tools_used: vec!["test".to_string()],
                errors: vec![],
            },
            diff: None,
        };
        // Finalize to populate files array
        report.finalize();
        report
    }

    #[test]
    fn test_aggregate_findings_empty() {
        let findings: Vec<Finding> = vec![];
        let aggregated = aggregate_findings_by_directory(&findings);
        assert_eq!(aggregated.len(), 0);
    }

    #[test]
    fn test_aggregate_findings_different_directories() {
        let findings = vec![
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "execution/shell::bash-variant".to_string(),
                desc: "Execute bash".to_string(),
                conf: 0.9,
                crit: Criticality::Hostile,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "net/http::get-variant".to_string(),
                desc: "HTTP GET request".to_string(),
                conf: 0.8,
                crit: Criticality::Suspicious,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
        ];
        let aggregated = aggregate_findings_by_directory(&findings);
        assert_eq!(aggregated.len(), 2);
        // IDs should be base trait IDs (without ::variant suffix)
        let ids: Vec<_> = aggregated.iter().map(|f| f.id.as_str()).collect();
        assert!(ids.contains(&"execution/shell"));
        assert!(ids.contains(&"net/http"));
    }

    #[test]
    fn test_aggregate_findings_same_directory_keeps_highest_criticality() {
        let findings = vec![
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "execution/shell::bash-variant".to_string(),
                desc: "Execute bash".to_string(),
                conf: 0.7,
                crit: Criticality::Suspicious,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "execution/shell::sh-variant".to_string(),
                desc: "Execute sh".to_string(),
                conf: 0.7,
                crit: Criticality::Hostile,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
        ];
        let aggregated = aggregate_findings_by_directory(&findings);
        assert_eq!(aggregated.len(), 1);
        assert_eq!(aggregated[0].id, "execution/shell");
        assert_eq!(aggregated[0].crit, Criticality::Hostile);
        // Should have both trait IDs in trait_refs
        assert_eq!(aggregated[0].trait_refs.len(), 2);
    }

    #[test]
    fn test_aggregate_findings_same_directory_keeps_highest_confidence() {
        let findings = vec![
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "execution/shell::bash-variant".to_string(),
                desc: "Execute bash".to_string(),
                conf: 0.6,
                crit: Criticality::Hostile,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "execution/shell::sh-variant".to_string(),
                desc: "Execute sh".to_string(),
                conf: 0.9,
                crit: Criticality::Hostile,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
        ];
        let aggregated = aggregate_findings_by_directory(&findings);
        assert_eq!(aggregated.len(), 1);
        assert_eq!(aggregated[0].id, "execution/shell");
        assert_eq!(aggregated[0].conf, 0.9);
    }

    #[test]
    fn test_risk_indicator() {
        // Verify the underlying text content (colored strings deref to &str).
        // `·` (small dot) marks the minor tiers (component/baseline); `•` is
        // notable; the dot count rises with severity.
        assert_eq!(&*risk_indicator(&Criticality::Component), "  ·");
        assert_eq!(&*risk_indicator(&Criticality::Baseline), "  ·");
        assert_eq!(&*risk_indicator(&Criticality::Notable), "  •");
        assert_eq!(&*risk_indicator(&Criticality::Suspicious), " ••");
        assert_eq!(&*risk_indicator(&Criticality::Hostile), "•••");
    }

    #[test]
    fn test_split_trait_id() {
        let (ns, rest) = split_trait_id("intel/discover/process");
        assert_eq!(ns, "intel");
        assert_eq!(rest, "discover/process");
    }

    #[test]
    fn test_split_trait_id_no_namespace() {
        let (ns, rest) = split_trait_id("test");
        assert_eq!(ns, "test");
        assert_eq!(rest, "test");
    }

    #[test]
    fn test_namespace_long_name() {
        assert_eq!(namespace_long_name("c2"), "COMMAND & CONTROL");
        assert_eq!(namespace_long_name("discovery"), "DISCOVERY");
        assert_eq!(namespace_long_name("crypto"), "CRYPTOGRAPHY");
        assert_eq!(namespace_long_name("credential-access"), "CREDENTIALS");
        assert_eq!(namespace_long_name("anti-static"), "STATIC EVASION");
        assert_eq!(namespace_long_name("comm"), "COMMUNICATION");
        assert_eq!(namespace_long_name("collect"), "COLLECTION");
        assert_eq!(namespace_long_name("impact"), "IMPACT");
        assert_eq!(namespace_long_name("meta"), "METADATA");
        assert_eq!(namespace_long_name("unknown"), "UNKNOWN");
    }

    #[test]
    fn test_format_evidence_empty() {
        let trait_item = Finding {
            kind: FindingKind::Capability,
            trait_refs: vec![],
            id: "test".to_string(),
            desc: "Test trait".to_string(),
            conf: 0.8,
            crit: Criticality::Notable,
            mbc: None,
            attack: None,
            evidence: vec![],
            match_count: 0,
            source_file: None,
        };
        assert_eq!(format_evidence(&trait_item), "");
    }

    #[test]
    fn test_format_evidence_with_values() {
        let trait_item = Finding {
            kind: FindingKind::Capability,
            trait_refs: vec![],
            id: "test".to_string(),
            desc: "Test".to_string(),
            conf: 0.8,
            crit: Criticality::Notable,
            mbc: None,
            attack: None,
            evidence: vec![
                Evidence {
                    method: "yara".to_string(),
                    source: "test".to_string(),
                    value: "cmd.exe".to_string(),
                    location: None,
                    ..Default::default()
                },
                Evidence {
                    method: "yara".to_string(),
                    source: "test".to_string(),
                    value: "powershell".to_string(),
                    location: None,
                    ..Default::default()
                },
            ],
            match_count: 2,
            source_file: None,
        };
        let formatted = format_evidence(&trait_item);
        assert!(formatted.contains("cmd.exe"));
        assert!(formatted.contains("powershell"));
    }

    #[test]
    fn test_format_terminal_empty_report() {
        let report = create_test_report(vec![], vec![]);
        let output = format_terminal(&report);
        assert!(output.is_empty());
    }

    #[test]
    fn test_format_terminal_with_capabilities() {
        let capabilities = vec![Finding {
            kind: FindingKind::Capability,
            trait_refs: vec![],
            id: "micro-behaviors/execution/shell".to_string(),
            desc: "Execute shell commands".to_string(),
            conf: 0.9,
            crit: Criticality::Hostile,
            mbc: None,
            attack: None,
            evidence: vec![],
            match_count: 0,
            source_file: None,
        }];
        let report = create_test_report(capabilities, vec![]);
        let output = format_terminal(&report);
        assert!(output.contains("execution/shell") || output.contains("MICRO-BEHAVIORS"));
    }

    #[test]
    fn test_format_terminal_includes_third_party() {
        let findings = vec![Finding {
            kind: FindingKind::Indicator,
            trait_refs: vec![],
            id: "third_party/Sekoia/Backdoor/Lin/Bpfdoor".to_string(),
            desc: "Detect the BPFDoor backdoor".to_string(),
            conf: 0.95,
            crit: Criticality::Hostile,
            mbc: None,
            attack: None,
            evidence: vec![Evidence {
                method: "yara".to_string(),
                source: "test".to_string(),
                value: "$op1".to_string(),
                location: None,
                ..Default::default()
            }],
            match_count: 1,
            source_file: None,
        }];
        let report = create_test_report(findings, vec![]);

        let output = format_terminal(&report);

        assert!(output.contains("THIRD-PARTY"));
        assert!(output.contains("Sekoia/Backdoor/Lin/Bpfdoor"));
        assert!(!output.contains("third_party/Sekoia"));
    }

    #[test]
    fn test_format_tiny_includes_description_as_tsv_field() {
        let findings = vec![Finding {
            kind: FindingKind::Capability,
            trait_refs: vec![],
            id: "micro-behaviors/process/create/shell::bash".to_string(),
            desc: "Execute shell commands".to_string(),
            conf: 0.9,
            crit: Criticality::Notable,
            mbc: None,
            attack: None,
            evidence: vec![Evidence {
                method: "symbol".to_string(),
                source: "test".to_string(),
                value: "bash\nwith\twhitespace".to_string(),
                location: None,
                ..Default::default()
            }],
            match_count: 1,
            source_file: None,
        }];
        let report = create_test_report(findings, vec![]);

        let output = format_tiny(&report);

        // No capture pass ran here, so the finding has no context window and
        // renders as a `.` no-anchor line carrying its description (the trait-id
        // leaf was dropped in the context-centric rewrite).
        assert!(output.contains("/test/sample.bin\tELF 12KB"));
        assert!(output.contains(". # N Execute shell commands"));
    }

    #[test]
    fn test_format_tiny_includes_baseline_and_composite_findings() {
        let findings = vec![
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "micro-behaviors/fs/read::open".to_string(),
                desc: "Open file for reading".to_string(),
                conf: 0.8,
                crit: Criticality::Baseline,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "micro-behaviors/fs/read::open".to_string(),
                desc: "Open file for reading".to_string(),
                conf: 0.8,
                crit: Criticality::Baseline,
                mbc: None,
                attack: None,
                evidence: vec![Evidence {
                    method: "symbol".to_string(),
                    source: "test".to_string(),
                    value: "fopen".to_string(),
                    location: None,
                    ..Default::default()
                }],
                match_count: 0,
                source_file: None,
            },
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "objectives/execution/loader::fragment".to_string(),
                desc: "Loader fragment".to_string(),
                conf: 0.7,
                crit: Criticality::Component,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "objectives/execution/loader::unused-fragment".to_string(),
                desc: "Unused loader fragment".to_string(),
                conf: 0.7,
                crit: Criticality::Component,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
            Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![
                    "micro-behaviors/fs/read::open".to_string(),
                    "objectives/execution/loader::fragment".to_string(),
                ],
                id: "objectives/execution/loader::matched-composite".to_string(),
                desc: "Matched composite loader".to_string(),
                conf: 0.95,
                crit: Criticality::Suspicious,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            },
        ];
        let report = create_test_report(findings, vec![]);

        let output = format_tiny(&report);

        // No capture pass, so findings render as `.` no-anchor lines — but only
        // Notable+ ones. The Baseline reads and both Components are filtered out;
        // only the matched composite (Suspicious) survives.
        assert!(!output.contains("micro-behaviors/fs/read::open"));
        assert!(!output.contains("objectives/execution/loader::fragment"));
        assert!(!output.contains("objectives/execution/loader::unused-fragment"));
        // No-anchor lines now carry the description, not the trait id.
        assert!(output.contains(". # S Matched composite loader"));
    }

    #[test]
    fn test_format_tiny_merges_and_annotates_context() {
        // A file with merged context: two findings on one line (collision) and
        // a context line between two hits.
        use crate::types::{ContextLine, Note};
        let report = create_test_report(
            vec![Finding {
                kind: FindingKind::Capability,
                trait_refs: vec![],
                id: "net/socket".to_string(),
                desc: "socket usage".to_string(),
                conf: 0.8,
                crit: Criticality::Notable,
                mbc: None,
                attack: None,
                evidence: vec![],
                match_count: 0,
                source_file: None,
            }],
            vec![],
        );
        // Inject context directly (the capture pass needs file bytes).
        let mut report = report;
        report.files[0].context = vec![
            ContextLine {
                loc: 4,
                addr: Some(40),
                text: "ctx before".to_string(),
                hex: false,
                notes: vec![],
            },
            ContextLine {
                loc: 5,
                addr: Some(55),
                text: "s = socket()".to_string(),
                hex: false,
                notes: vec![Note {
                    crit: Criticality::Notable,
                    id: "net/socket".to_string(),
                    desc: "socket usage".to_string(),
                    off: 60,
                    len: 8,
                    conf: 0.8,
                }],
            },
        ];
        let output = format_tiny(&report);
        assert!(output.contains("4- ctx before"));
        // Annotation is the description in the sample's comment marker (`//` for
        // binary), not the trait-id leaf.
        assert!(output.contains("5: s = socket() // N socket usage"));
    }
}
