//! Random-string detection for identifier-like fields.
//!
//! Answers one question: does this string read like a name someone chose, or
//! like output from a generator? It exists for the surfaces where an attacker
//! must supply *some* identifier and picks a random one — DGA domain labels,
//! document `Author` fields written by a maldoc builder, bundle identifiers,
//! generated mutex and service names, hash-named artifacts.
//!
//! # Method
//!
//! Mean log10 P(next | prev) over the string's letter transitions, against an
//! English bigram model with start/end markers, add-one smoothed. Boundary
//! markers matter: they capture that real names begin and end on plausible
//! letters, and adding them moved the worst DGA sample from -1.91 to -2.01,
//! clearing the decision threshold.
//!
//! Character entropy was measured first and rejected. At these lengths it is
//! useless — nearly every 8-character string has all-distinct characters, so
//! Shannon entropy pins at 1.0 for `kwTfNTTv` and `McDonald` alike. Vowel
//! ratio separates better but still convicts `SYSTEM`, `Dell` and `HP Inc.`.
//! Bigram plausibility is the only signal measured that works on short input.
//!
//! # Limits
//!
//! The model is English. Consonant-dense names from other languages score
//! low, and `Krzysztof` (-2.19) is the one string in a 70-item control set
//! that crosses the threshold. Anything reached by this validator should be
//! evidence, not a verdict. Strings shorter than [`MIN_LEN`] letters are
//! never called random: three letters carry no evidence either way.
//!
//! The table is regenerated by `scripts/gen_bigram_table.py` from English
//! prose; see that script for the corpus.

/// Alphabet: start marker, `a`-`z`, end marker.
const ALPHA: usize = 28;
const START: usize = 0;
const END: usize = 27;

/// Shortest run of letters that carries enough transitions to judge.
pub const MIN_LEN: usize = 6;

/// Mean log10 transition probability at or below which a string reads as
/// generated. Chosen from the measured gap: the least-random DGA sample
/// scores -2.01, the most-random ordinary name (excluding `Krzysztof`)
/// scores -1.82.
pub const RANDOM_THRESHOLD: f64 = -2.0;

/// log10 P(col | row) over `ALPHA` symbols, add-one smoothed.
///
/// Generated data, not hand-written constants: `approx_constant` fires
/// because two of the 784 probabilities land near e and pi.
#[allow(clippy::approx_constant)]
#[rustfmt::skip]
static BIGRAM_LOGP: [[f32; ALPHA]; ALPHA] = [
    // START
    [-5.745, -1.189, -1.419, -1.044, -1.288, -1.283, -1.376, -1.697, -1.499, -1.355, -1.906, -1.978, -1.449, -1.306, -1.470, -1.548, -1.018, -2.413, -1.185, -1.008, -1.305, -1.667, -1.710, -1.465, -2.478, -3.006, -2.582, -5.745],
    // a
    [-5.406, -3.316, -1.569, -1.088, -1.173, -2.499, -2.412, -1.225, -3.262, -1.548, -3.278, -2.307, -1.043, -1.236, -1.012, -3.215, -1.384, -3.044, -0.941, -1.200, -0.824, -1.699, -1.772, -2.155, -2.785, -1.705, -2.847, -1.399],
    // b
    [-4.748, -0.880, -2.476, -1.964, -2.394, -0.966, -1.585, -2.719, -2.388, -1.118, -1.599, -2.963, -0.910, -2.467, -2.942, -1.032, -1.901, -3.970, -1.075, -1.448, -2.641, -1.001, -2.744, -3.602, -3.049, -1.248, -3.257, -1.033],
    // c
    [-5.221, -1.043, -3.187, -1.860, -2.718, -0.895, -2.869, -3.297, -1.064, -1.804, -3.465, -1.065, -1.278, -2.350, -3.135, -0.679, -2.110, -3.653, -1.081, -2.185, -0.971, -1.370, -2.940, -3.558, -3.473, -2.036, -4.920, -1.300],
    // d
    [-5.153, -1.324, -2.007, -2.286, -1.558, -0.586, -2.241, -2.386, -2.954, -1.160, -3.148, -2.431, -1.584, -2.203, -2.217, -1.171, -1.825, -4.675, -1.573, -1.443, -2.689, -1.540, -2.695, -2.671, -3.314, -2.111, -3.490, -0.471],
    // e
    [-5.620, -1.535, -2.049, -1.237, -1.215, -2.091, -1.757, -1.919, -2.686, -2.617, -3.680, -3.369, -1.324, -1.518, -0.939, -2.869, -1.918, -2.271, -0.816, -1.031, -1.312, -2.871, -1.967, -2.388, -1.333, -2.084, -3.369, -0.653],
    // f
    [-4.747, -1.287, -2.947, -2.597, -2.387, -0.870, -1.411, -3.123, -3.667, -0.462, -3.667, -2.734, -1.372, -2.895, -3.065, -0.941, -2.738, -3.901, -1.208, -1.942, -1.424, -1.201, -4.144, -3.144, -2.597, -2.174, -3.705, -1.135],
    // g
    [-4.818, -1.575, -2.651, -2.371, -2.547, -0.490, -3.055, -1.774, -1.644, -0.988, -4.517, -3.421, -1.696, -1.854, -1.309, -1.186, -2.387, -3.739, -1.362, -1.696, -2.426, -1.491, -2.715, -2.869, -3.642, -2.637, -2.625, -0.627],
    // h
    [-4.881, -0.962, -2.978, -2.602, -2.260, -0.625, -3.301, -3.705, -3.418, -1.044, -3.802, -2.951, -2.648, -2.095, -2.589, -0.825, -1.722, -2.983, -1.510, -2.294, -1.288, -1.602, -3.247, -3.061, -3.802, -2.394, -3.802, -0.600],
    // i
    [-5.349, -1.502, -1.755, -1.256, -1.375, -1.464, -1.696, -1.546, -3.792, -3.187, -2.863, -2.575, -1.115, -1.483, -0.665, -0.954, -1.354, -3.108, -1.530, -1.279, -0.996, -2.689, -1.451, -3.608, -2.031, -3.934, -1.971, -1.370],
    // j
    [-4.047, -0.528, -2.705, -1.723, -2.227, -0.615, -2.570, -3.269, -3.445, -1.757, -2.685, -2.585, -2.414, -2.585, -2.118, -1.382, -1.979, -2.315, -2.434, -0.628, -3.570, -1.496, -1.308, -2.155, -2.817, -3.445, -3.570, -2.123],
    // k
    [-4.620, -0.891, -2.231, -2.341, -1.768, -0.412, -2.072, -1.950, -2.801, -1.126, -3.717, -3.129, -2.268, -2.272, -2.034, -1.879, -2.480, -3.921, -2.523, -1.359, -1.881, -1.729, -2.913, -2.913, -4.143, -2.403, -3.842, -0.623],
    // l
    [-5.201, -1.103, -2.288, -2.368, -1.476, -0.695, -2.020, -3.104, -2.927, -0.955, -3.644, -2.641, -0.942, -2.417, -2.387, -0.926, -1.908, -4.201, -2.906, -1.627, -1.631, -1.549, -2.361, -2.628, -3.362, -1.751, -3.232, -0.708],
    // m
    [-5.020, -0.708, -1.390, -2.296, -1.979, -0.604, -2.587, -2.956, -3.429, -1.161, -3.133, -3.249, -1.931, -1.304, -2.816, -1.077, -1.026, -3.357, -2.779, -1.677, -2.547, -1.717, -3.091, -2.311, -3.264, -2.527, -3.175, -0.890],
    // n
    [-5.338, -1.077, -2.905, -1.183, -1.001, -1.127, -1.772, -1.181, -2.935, -1.534, -2.364, -2.106, -1.969, -2.223, -1.825, -1.610, -1.880, -3.846, -2.732, -1.122, -0.818, -1.903, -1.844, -2.941, -2.641, -2.392, -3.463, -0.666],
    // o
    [-5.364, -1.412, -1.689, -1.352, -1.178, -2.997, -1.775, -1.745, -3.126, -1.796, -2.416, -1.624, -1.435, -1.165, -0.692, -1.427, -1.461, -4.188, -0.875, -1.387, -1.461, -1.333, -1.909, -1.384, -2.115, -2.741, -3.174, -1.296],
    // p
    [-5.131, -0.735, -2.336, -2.227, -1.913, -0.944, -2.424, -2.777, -1.650, -1.274, -3.788, -2.322, -1.238, -1.816, -2.525, -0.955, -1.464, -4.052, -0.982, -1.831, -1.123, -1.621, -2.691, -3.013, -2.794, -1.398, -4.176, -0.962],
    // q
    [-3.798, -2.652, -2.418, -2.953, -2.519, -1.953, -3.798, -3.497, -3.497, -2.455, -3.099, -3.798, -1.011, -2.719, -1.255, -2.652, -2.400, -2.497, -2.895, -2.418, -1.884, -0.122, -2.497, -2.108, -2.953, -3.321, -3.798, -1.645],
    // r
    [-5.395, -1.074, -2.627, -1.473, -1.634, -0.677, -2.508, -1.846, -3.391, -1.066, -4.441, -1.537, -1.754, -1.793, -1.888, -1.006, -2.241, -4.165, -2.051, -1.449, -1.450, -1.507, -1.842, -2.622, -3.441, -1.285, -4.395, -0.740],
    // s
    [-5.346, -1.752, -2.781, -1.296, -2.355, -0.928, -2.579, -3.033, -1.283, -1.178, -3.931, -1.929, -2.268, -2.243, -2.722, -1.311, -1.665, -2.319, -2.778, -1.191, -0.788, -1.760, -2.815, -2.106, -3.012, -1.698, -3.815, -0.511],
    // t
    [-5.422, -1.053, -2.804, -1.819, -2.468, -0.791, -2.462, -3.243, -1.034, -0.866, -3.798, -2.820, -2.110, -2.406, -2.669, -1.170, -1.792, -4.079, -1.194, -1.463, -1.635, -1.720, -3.405, -2.288, -3.051, -1.638, -3.524, -0.644],
    // u
    [-4.948, -1.579, -1.289, -1.544, -1.614, -1.250, -2.083, -1.591, -3.625, -1.368, -3.772, -3.141, -1.182, -1.365, -0.838, -2.712, -1.257, -3.948, -0.829, -0.947, -0.852, -2.935, -3.232, -4.471, -2.018, -3.567, -3.177, -2.021],
    // v
    [-4.603, -0.723, -1.631, -2.240, -2.679, -0.382, -2.990, -2.654, -3.302, -0.713, -4.302, -3.223, -2.546, -1.510, -2.728, -1.498, -2.251, -4.603, -2.700, -1.568, -2.570, -2.442, -3.047, -3.524, -2.804, -2.405, -3.700, -1.293],
    // w
    [-4.587, -1.019, -2.996, -2.546, -2.243, -0.924, -2.724, -2.271, -1.569, -0.597, -4.587, -2.897, -2.375, -2.015, -1.189, -0.923, -2.227, -3.441, -1.112, -0.924, -2.378, -3.031, -4.286, -3.082, -2.311, -3.633, -4.110, -1.123],
    // x
    [-4.454, -1.809, -2.898, -1.644, -2.364, -0.687, -1.311, -3.039, -2.801, -1.664, -3.175, -3.551, -2.568, -1.684, -3.199, -1.530, -1.090, -3.977, -2.852, -2.390, -0.642, -2.852, -3.250, -2.585, -2.730, -1.663, -3.132, -0.554],
    // y
    [-4.699, -2.066, -2.102, -2.015, -2.666, -2.145, -2.666, -2.294, -3.056, -2.339, -3.553, -3.585, -1.218, -1.550, -1.579, -2.109, -1.032, -3.398, -2.266, -1.116, -1.023, -2.638, -3.237, -1.883, -3.155, -3.620, -2.854, -0.268],
    // z
    [-3.732, -1.071, -2.887, -2.502, -2.502, -0.360, -2.528, -2.618, -1.887, -0.685, -3.255, -3.130, -1.732, -2.099, -2.586, -1.341, -2.502, -3.130, -2.317, -1.707, -2.214, -1.592, -3.732, -2.285, -2.410, -1.778, -1.919, -1.145],
    // END
    [-1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447, -1.447],
];

/// Map a byte to its index in [`BIGRAM_LOGP`], or `None` if not a letter.
fn index_of(b: u8) -> Option<usize> {
    match b {
        b'a'..=b'z' => Some((b - b'a') as usize + 1),
        b'A'..=b'Z' => Some((b - b'A') as usize + 1),
        _ => None,
    }
}

/// Longest consecutive run of ASCII letters in `s`.
///
/// A matched span is rarely just the identifier: a DGA hit arrives as
/// `kqjxwvbnmz.com`, and scoring the whole span would average the random
/// label against the very ordinary `com`. Taking the longest run picks the
/// label out on its own.
fn longest_letter_run(s: &str) -> &str {
    let bytes = s.as_bytes();
    let (mut best_start, mut best_len) = (0usize, 0usize);
    let (mut start, mut len) = (0usize, 0usize);
    for (i, &b) in bytes.iter().enumerate() {
        if index_of(b).is_some() {
            if len == 0 {
                start = i;
            }
            len += 1;
            if len > best_len {
                best_start = start;
                best_len = len;
            }
        } else {
            len = 0;
        }
    }
    &s[best_start..best_start + best_len]
}

/// Mean log10 transition probability of the longest letter run in `s`.
///
/// Returns `None` when that run is shorter than [`MIN_LEN`]. Higher is more
/// word-like; scores run from roughly -0.8 (ordinary English) to -3.0.
#[must_use]
pub fn random_score(s: &str) -> Option<f64> {
    let run = longest_letter_run(s);
    if run.len() < MIN_LEN {
        return None;
    }
    let idx: Vec<usize> = run.bytes().filter_map(index_of).collect();
    let mut sum = 0.0f64;
    let mut prev = START;
    for &i in &idx {
        sum += f64::from(BIGRAM_LOGP[prev][i]);
        prev = i;
    }
    sum += f64::from(BIGRAM_LOGP[prev][END]);
    Some(sum / (idx.len() + 1) as f64)
}

/// Whether `s` reads as generated rather than chosen.
///
/// Conservative by construction: too short to judge is not random.
#[must_use]
pub fn is_random_like(s: &str) -> bool {
    random_score(s).is_some_and(|v| v < RANDOM_THRESHOLD)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Author fields from a 40-sample abuse.ch `.xls` wave. The builder
    /// randomizes the Office `Author` property; these are the values it wrote.
    const MALDOC_AUTHORS: &[&str] = &[
        "kwTfNTTv",
        "ziqTjNCrvh",
        "LHLiSEls",
        "RhgSiBU",
        "nyffwuOC",
        "iwmKdN",
        "qoPhrreWk",
        "QDnqfZpMxb",
        "RctHQGiE",
        "mhgFhzbVJl",
        "nLkGocK",
        "CzNhkXKdg",
        "QxQeiKeMUe",
        "auCRDXUq",
        "wbjSLQSbu",
        "bAUiDP",
        "ljfAVhV",
        "ZsVTxgT",
        "dXkHst",
        "KfrnXWP",
        "WVzDCSU",
        "IaAojIoVZC",
        "nmdHLS",
        "jATcthbx",
        "BimTqdt",
        "NJvHAsYIMI",
    ];

    /// Algorithmically generated domain labels.
    const DGA_LABELS: &[&str] = &[
        "xeogrmcsyyaw",
        "lrkzcvmqxo",
        "qwnvdlbtkr",
        "vpxksmnwqz",
        "kqjxwvbnmz",
        "ffxvhsbkxr",
        "zjqhdvmrbk",
        "nawbtcxrgd",
        "mxvbkqzjfd",
        "hjkxwqvbnm",
        "dkwmzqxvbr",
        "tqzjxvmwkb",
    ];

    /// Names, brands and ordinary words that must never be called generated.
    /// Deliberately not all English: the model is English, so non-English
    /// surnames are where it is weakest and where regressions will show first.
    const LEGITIMATE: &[&str] = &[
        "Toshiba",
        "Lenovo",
        "Compaq",
        "Microsoft",
        "Realtek",
        "Logitech",
        "Administrator",
        "McDonald",
        "Johnson",
        "Sullivan",
        "Anderson",
        "Williams",
        "Nguyen",
        "Wojciech",
        "Dvorak",
        "Rajesh",
        "Priyanka",
        "Mohammed",
        "Ivanov",
        "Mueller",
        "Gonzalez",
        "Oliveira",
        "Yamamoto",
        "Takahashi",
        "Kowalski",
        "Mikhail",
        "Sanchez",
        "Fernandez",
        "Okonkwo",
        "Siddiqui",
        "Bhattacharya",
        "Ramaswamy",
        "Papadopoulos",
        "Kalinowski",
        "Horvath",
        "powerpoint",
        "outlook",
        "windows",
        "desktop",
        "invoice",
        "receipt",
        "calculator",
        "document",
        "template",
        "finance",
        "chrome",
        "firefox",
        "notepad",
    ];

    #[test]
    fn flags_every_dga_label() {
        for s in DGA_LABELS {
            assert!(is_random_like(s), "{s} should read as generated");
        }
    }

    #[test]
    fn clears_legitimate_names_and_words() {
        let missed: Vec<_> = LEGITIMATE.iter().filter(|s| is_random_like(s)).collect();
        assert!(missed.is_empty(), "false positives: {missed:?}");
    }

    /// Not all of them: several are three to five letters, which the length
    /// floor declines to judge, and a few are genuinely pronounceable. The
    /// bar is a clear majority, not perfection -- overfitting the threshold
    /// to this corpus is what the legitimate-name test exists to prevent.
    #[test]
    fn flags_most_maldoc_authors() {
        let hits = MALDOC_AUTHORS.iter().filter(|s| is_random_like(s)).count();
        assert!(
            hits * 2 > MALDOC_AUTHORS.len(),
            "only {hits}/{} flagged",
            MALDOC_AUTHORS.len()
        );
    }

    #[test]
    fn separates_the_two_populations() {
        let worst_dga = DGA_LABELS
            .iter()
            .filter_map(|s| random_score(s))
            .fold(f64::NEG_INFINITY, f64::max);
        let best_legit = LEGITIMATE
            .iter()
            .filter_map(|s| random_score(s))
            .fold(f64::INFINITY, f64::min);
        // The gap is narrow and real. If a corpus change closes it, the
        // threshold is no longer defensible and this fails loudly.
        assert!(
            worst_dga < RANDOM_THRESHOLD,
            "least-random DGA scored {worst_dga}"
        );
        assert!(
            best_legit > -2.3,
            "most-random legitimate scored {best_legit}"
        );
    }

    #[test]
    fn too_short_is_never_random() {
        // Three letters carry no evidence. Refusing to judge is the point.
        for s in ["AXn", "DaT", "CnI", "rsl", "Dell", "admin", "IBM", "x"] {
            assert!(!is_random_like(s), "{s} is too short to judge");
            assert!(random_score(s).is_none(), "{s} should have no score");
        }
    }

    #[test]
    fn scores_the_longest_letter_run() {
        // A DGA hit arrives with its TLD attached; averaging the random label
        // against `com` would pull it back over the threshold.
        assert_eq!(longest_letter_run("kqjxwvbnmz.com"), "kqjxwvbnmz");
        assert_eq!(longest_letter_run("a-longestrun-b"), "longestrun");
        assert_eq!(longest_letter_run("12345"), "");
        assert!(is_random_like("kqjxwvbnmz.com"));
    }

    #[test]
    fn ignores_case() {
        assert_eq!(random_score("KQJXWVBNMZ"), random_score("kqjxwvbnmz"));
        assert_eq!(random_score("Microsoft"), random_score("microsoft"));
    }

    #[test]
    fn handles_non_ascii_without_panicking() {
        for s in ["日本語テキスト", "Ünïcödé", "", "→→→", "Ivan\u{00ed}"] {
            let _ = is_random_like(s);
        }
    }
}
